# Setup

In [1]:
%env N_EX=64

env: N_EX=64

# Candidates

In [2]:
%%writefile get_candidates.py

import sys

sys.path.insert(0, "/kaggle/input/mdc-utils-v02/code")

import argparse
import os
import sys
from pathlib import Path

import pandas as pd
from omegaconf import OmegaConf
from utils.ingest_utils import _find_dataset_positions, check_presence, get_all_hits, load_data  # type: ignore
from vllm import LLM, SamplingParams

DOI_FIXER_PROMPT = "Extract the DOI from the provided text."


def sanitize_doi(row):
    org_doi = row["dataset_id"]
    doi_fixed = row["dataset_id_fixed"]
    if org_doi == doi_fixed:
        return org_doi

    pos = _find_dataset_positions(row["text"], doi_fixed.replace("https://doi.org/", ""))
    if len(pos) == 0:
        return org_doi

    if len(org_doi) >= len(doi_fixed):
        return org_doi
    if " " in doi_fixed:
        return org_doi
    return doi_fixed


def get_candidates(input_df, doi_bank, acc_bank, whitelist):
    doi_group_df = doi_bank.groupby("article_id")["dataset_id"].agg(list).reset_index()
    acc_group_df = acc_bank.groupby("article_id")["dataset_id"].agg(list).reset_index()

    dataset2family = dict(zip(acc_bank["dataset_id"], acc_bank["family"]))
    for doi in doi_bank["dataset_id"]:
        if doi not in dataset2family:
            dataset2family[doi] = "doi"

    article2doi = dict(zip(doi_group_df["article_id"], doi_group_df["dataset_id"]))
    article2acc = dict(zip(acc_group_df["article_id"], acc_group_df["dataset_id"]))

    hit_data = []
    for _, row in input_df.iterrows():
        article_id = row["article_id"]
        pdf_text = row["pdf_text"]
        xml_text = row["xml_text"]

        # try online lookup ---
        doi_hits = article2doi.get(article_id, [])
        acc_hits = article2acc.get(article_id.lower(), [])

        all_hits = list(set(doi_hits + acc_hits))

        selected_hits = []
        for hit in all_hits:
            if check_presence(pdf_text, hit) or check_presence(xml_text, hit):
                selected_hits.append(hit)

        if len(selected_hits) > 0:
            hit_data.extend([{"article_id": article_id, "dataset_id": hit} for hit in selected_hits])
            continue

        # look for match using regex
        pdf_hits = get_all_hits(pdf_text, whitelist=whitelist)
        xml_hits = get_all_hits(xml_text, whitelist=whitelist)
        all_hits = list(set(pdf_hits + xml_hits))
        hit_data.extend([{"article_id": article_id, "dataset_id": hit} for hit in all_hits])

    candidate_df = pd.DataFrame(hit_data)
    candidate_df["family"] = candidate_df["dataset_id"].map(dataset2family)
    candidate_df["family"] = candidate_df["family"].fillna("custom")
    candidate_df["family"] = candidate_df.apply(lambda row: "doi" if row["dataset_id"].startswith("https://doi.org") else row["family"], axis=1)
    return candidate_df


def fix_multiline_doi(cfg, candidate_df, input_df, offset=32):
    original_df = candidate_df.copy()
    focus_df = candidate_df[(candidate_df["family"] == "custom") & (candidate_df["dataset_id"].str.startswith("https://doi.org"))].reset_index(drop=True)
    print(f"# of DOI with custom family: {len(focus_df)}")

    if len(focus_df) == 0:
        return original_df

    # prepare data for doi fixer
    infer_data = []
    for _, row in focus_df.iterrows():
        article_id = row["article_id"]
        dataset_id = row["dataset_id"]
        text_row = input_df[input_df["article_id"] == article_id]

        text_pdf = text_row["pdf_text"].values[0]
        text_xml = text_row["xml_text"].values[0]
        text = text_pdf + text_xml

        search_id = dataset_id.replace("https://doi.org/", "")
        positions = _find_dataset_positions(text, search_id)[:2]  # take up to 2 positions
        for start, end in positions:
            window = text[start : end + offset]
            infer_data.append({"article_id": article_id, "dataset_id": dataset_id, "text": window})
    infer_df = pd.DataFrame(infer_data)

    # DOI Fixer LLM ---
    llm = LLM(
        model=cfg.doi_fixer_model,
        dtype="half",
        tensor_parallel_size=2,
        max_model_len=512,
        enforce_eager=True,
        gpu_memory_utilization=0.9,
        enable_prefix_caching=False,
        disable_log_stats=True,
        max_num_seqs=64,
        swap_space=0,
        cpu_offload_gb=0,
        max_num_batched_tokens=2048,
    )

    # create prompts ---
    prompts = []
    for _, row in infer_df.iterrows():
        user_message = f"# Text:\n\n{row['text']}"
        prompt = f"{DOI_FIXER_PROMPT}\n\n{user_message}\n\nAnswer:\n"
        prompts.append(prompt)

    # print a few prompts
    for p in prompts[:1]:
        print(p)
        print("-" * 100)

    batch_size = 4096
    extracted_doi_list = []

    for i in range(0, len(prompts), batch_size):
        batch_prompts = prompts[i : i + batch_size]
        print(f"Processing batch {i // batch_size + 1}/{(len(prompts) + batch_size - 1) // batch_size} (items {i + 1}-{min(i + batch_size, len(prompts))})")
        sampling_params = SamplingParams(temperature=0.0, skip_special_tokens=True, max_tokens=128)
        batch_outputs = llm.generate(batch_prompts, sampling_params=sampling_params, use_tqdm=True)

        for output in batch_outputs:
            extracted_doi_list.append(output.outputs[0].text)

    # fixed
    fixed_df = pd.DataFrame()
    fixed_df["article_id"] = infer_df["article_id"]
    fixed_df["dataset_id"] = infer_df["dataset_id"]
    fixed_df["family"] = "custom"
    fixed_df["text"] = infer_df["text"]
    fixed_df["dataset_id_fixed"] = extracted_doi_list
    fixed_df["dataset_id_fixed"] = fixed_df["dataset_id_fixed"].apply(lambda x: f"https://doi.org/{x}")
    fixed_df["dataset_id_fixed"] = fixed_df.apply(sanitize_doi, axis=1)

    fixed_df = fixed_df[["article_id", "dataset_id_fixed", "family"]].rename(columns={"dataset_id_fixed": "dataset_id"})

    candidate_df = pd.concat([fixed_df, original_df]).reset_index(drop=True)
    candidate_df = candidate_df.drop_duplicates(subset=["article_id", "dataset_id"], keep="first").reset_index(drop=True)

    return candidate_df


def main(cfg):
    if os.getenv("KAGGLE_IS_COMPETITION_RERUN"):
        data_dir = Path("/kaggle/input/make-data-count-finding-data-references/test")
    else:
        data_dir = Path("/kaggle/input/make-data-count-finding-data-references/train")

    cache_dir = Path("cache")
    cache_dir.mkdir(parents=True, exist_ok=True)

    input_df = load_data(data_dir, cache_dir)

    if not os.getenv("KAGGLE_IS_COMPETITION_RERUN"):
        input_df = input_df.sort_values(by="article_id").reset_index(drop=True)
        n_ex = int(os.getenv("N_EX"))
        input_df = input_df.head(n_ex)

    current_ids = set(input_df["article_id"].tolist())
    current_ids_lower = set(x.lower() for x in current_ids)

    print(f"# of articles: {len(current_ids)}")

    # helper data ---
    whitelist_df = pd.read_parquet(cfg.whitelist_path)
    whitelist = whitelist_df["prefix"].tolist()

    doi_index_df = pd.read_parquet(cfg.doi_lookup_path)
    acc_index_df = pd.read_parquet(cfg.acc_lookup_path)

    doi_bank = doi_index_df[doi_index_df["article_id"].isin(current_ids)].reset_index(drop=True)
    acc_bank = acc_index_df[acc_index_df["article_id"].isin(current_ids_lower)].reset_index(drop=True)

    print("--" * 50)
    print(f"# of articles DOI found: {doi_bank['article_id'].nunique()} / {len(current_ids)}")
    print(f"# of articles ACC found: {acc_bank['article_id'].nunique()} / {len(current_ids)}")

    candidate_df = get_candidates(input_df, doi_bank, acc_bank, whitelist)
    candidate_df = candidate_df[candidate_df["family"] != "rrid"].reset_index(drop=True)  # remove rrid

    print("--" * 50)
    print(f"# of candidate documents: {len(candidate_df)}")
    print(candidate_df["family"].value_counts())
    print("--" * 50)

    print("Fixing multiline DOI...")
    print(f"shape before fixing: {candidate_df.shape}")
    candidate_df = fix_multiline_doi(cfg, candidate_df, input_df)
    print(f"shape after fixing: {candidate_df.shape}")

    # Save
    save_dir = cfg.save_dir
    save_path = os.path.join(save_dir, "candidates.parquet")
    candidate_df.to_parquet(save_path, index=False)
    print(f"saved online citations to: {save_path}")

    index_df = pd.concat([doi_bank[["article_id", "dataset_id"]], acc_bank[["article_id", "dataset_id"]]]).reset_index(drop=True)
    save_path = os.path.join(save_dir, "index.parquet")
    index_df.to_parquet(save_path, index=False)
    print("--" * 50)

    save_path = os.path.join(save_dir, "inputs.parquet")
    input_df.to_parquet(save_path, index=False)

    # save doi lookup for later use
    save_path = os.path.join(save_dir, "doi_bank.parquet")
    doi_bank.to_parquet(save_path, index=False)


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--config_path", type=str, default="conf/eval.yaml")
    args = parser.parse_args()

    cfg = OmegaConf.load(args.config_path)

    os.makedirs(cfg.save_dir, exist_ok=True)
    main(cfg)

Writing get_candidates.py

In [3]:
%%writefile config_candidates.yaml

save_dir: ./working
whitelist_path: /kaggle/input/mdc-data-doi-prefix/doi_prefix_whitelist.parquet
doi_lookup_path: /kaggle/input/mdc-corpus-processed-v3/index.parquet
acc_lookup_path: /kaggle/input/mdc-accession-bank/accession_bank.parquet
doi_fixer_model: /kaggle/input/mdc_doi_fixer/transformers/default/2

Writing config_candidates.yaml

In [4]:
%%time
!python get_candidates.py --config_path config_candidates.yaml

INFO 09-08 22:44:42 [__init__.py:244] Automatically detected platform cuda.
2025-09-08 22:44:44.247832: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:477] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1757371484.437838      72 cuda_dnn.cc:8310] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1757371484.490635      72 cuda_blas.cc:1418] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
Cache directory (cache/exp_tmp/txt) exists? -> False
MuPDF error: unsupported error: cannot create appearance stream for  annotations

MuPDF error: unsupported error: cannot create appearance stream for  annotations

MuPDF error: unsupported error: cannot create appearance stream for  annotations

MuPDF error: unsupported error: cannot create appearance stream for  annotations

MuPDF error: unsupported error: cannot create appearance stream for  annotations

MuPDF error: unsupported error: cannot create appearance stream for  annotations

MuPDF error: unsupported error: cannot create appearance stream for  annotations

MuPDF error: unsupported error: cannot create appearance stream for  annotations

MuPDF error: unsupported error: cannot create appearance stream for  annotations

MuPDF error: unsupported error: cannot create appearance stream for  annotations

MuPDF error: unsupported error: cannot create appearance stream for  annotations

MuPDF error: unsupported error: cannot create appearance stream for  annotations

MuPDF error: unsupported error: cannot create appearance stream for  annotations

MuPDF error: unsupported error: cannot create appearance stream for  annotations

MuPDF error: unsupported error: cannot create appearance stream for  annotations

MuPDF error: unsupported error: cannot create appearance stream for  annotations

MuPDF error: unsupported error: cannot create appearance stream for  annotations

MuPDF error: unsupported error: cannot create appearance stream for  annotations

# of previously processed files: 0
# of new files processed: 524
# of articles: 64
----------------------------------------------------------------------------------------------------
# of articles DOI found: 46 / 64
# of articles ACC found: 5 / 64
----------------------------------------------------------------------------------------------------
# of candidate documents: 103
family
doi             53
pdb             14
gen             11
chembl          10
geo              6
uniprot          3
custom           2
arrayexpress     2
hpa              2
Name: count, dtype: int64
----------------------------------------------------------------------------------------------------
Fixing multiline DOI...
shape before fixing: (103, 3)
# of DOI with custom family: 0
shape after fixing: (103, 3)
saved online citations to: ./working/candidates.parquet
----------------------------------------------------------------------------------------------------
CPU times: user 1.32 s, sys: 316 ms, total: 1.64 s
Wall time: 2min 13s

In [5]:
# import pandas as pd
# df = pd.read_parquet("./working/candidates.parquet")
# df # [article_id, dataset_id, familty]

# Filter

In [6]:
%%writefile filter_candidates.py

import sys

sys.path.insert(0, "/kaggle/input/mdc-utils-v02/code")

import argparse
import json
import os
import random
import re
import sys
from pathlib import Path

import numpy as np
import pandas as pd
import torch
from datasets import Dataset
from omegaconf import OmegaConf
from transformers import AutoTokenizer
from utils.ingest_utils import create_chunks, gt_dataset_id_normalization, load_data  # type: ignore
from vllm import LLM, SamplingParams  # type: ignore

SYS_PROMPT = """You are an expert at identifying research data citations in scientific literature. You excel at identifying and cataloging data citations in academic papers.

Your task is to determine whether a given DOI or Accession ID represents a valid citation based on the provided text context. Focus on identifying genuine data citations, not just any mention of an identifier."""

USER_TEMPLATE_W_DOI = """Text snippet: {context}

Detected DOI in the whole article: {detected_dois}

Focus DOI/Accession ID: {dataset_id}

Is {dataset_id} a valid research data citation in this text snippet?

Respond with only Yes or No"""

USER_TEMPLATE_WO_DOI = """Text snippet: {context}

Focus DOI/Accession ID: {dataset_id}

Is {dataset_id} a valid research data citation in this text snippet?

Respond with only Yes or No"""


def get_yes_prob(logprobs):
    yes_logit = None
    no_logit = None

    for _, logprob_obj in logprobs.items():
        token_str = logprob_obj.decoded_token.strip().lower()

        if token_str == "yes":
            if yes_logit is None:
                yes_logit = logprob_obj.logprob
        elif token_str == "no":
            if no_logit is None:
                no_logit = logprob_obj.logprob

    default_val = -20.0
    if yes_logit is None:
        yes_logit = default_val

    if no_logit is None:
        no_logit = default_val

    logits = np.array([yes_logit, no_logit])
    logits_max = np.max(logits)
    exp_logits = np.exp(logits - logits_max)
    normalized_scores = exp_logits / np.sum(exp_logits)

    return normalized_scores[0]


def get_chunk_hits(row, article2hits):
    aid = row["article_id"]
    chunk = row["chunk"]
    chunk = re.sub(r"\s+", "", chunk).lower()

    labels = article2hits.get(aid, [])

    ret = []
    for label in labels:
        search_id = gt_dataset_id_normalization(label)
        if search_id in chunk:
            ret.append(label)

    return ret


def get_doi_mapping(index_df):
    gdf = index_df.groupby("article_id")["dataset_id"].agg(set).reset_index()
    article2dataset_online = dict(zip(gdf["article_id"], gdf["dataset_id"]))

    article2doi_online = {k: [y for y in v if y.startswith("https://doi.org")] for k, v in article2dataset_online.items()}
    article2doi_online = {k: [y.replace("https://doi.org/", "") for y in v] for k, v in article2doi_online.items()}
    article2doi_online = {k: " | ".join(v) for k, v in article2doi_online.items()}

    return article2doi_online


def filter_fn(cfg, row):
    doi_th = cfg.doi_th

    acc_th = cfg.acc_th

    is_doi = row["dataset_id"].startswith("https://doi.org/")
    if is_doi:
        return row["yes_prob"] >= doi_th
    else:
        return row["yes_prob"] >= acc_th


def main(cfg):
    if os.getenv("KAGGLE_IS_COMPETITION_RERUN"):
        data_dir = Path("/kaggle/input/make-data-count-finding-data-references/test")
    else:
        data_dir = Path("/kaggle/input/make-data-count-finding-data-references/train")

    cache_dir = Path("cache")
    cache_dir.mkdir(parents=True, exist_ok=True)

    input_df = load_data(data_dir, cache_dir)

    if not os.getenv("KAGGLE_IS_COMPETITION_RERUN"):
        input_df = input_df.sort_values(by="article_id").reset_index(drop=True)
        n_ex = int(os.getenv("N_EX"))
        input_df = input_df.head(n_ex)

    # separate into custom vs non-custom
    hit_df = pd.read_parquet(cfg.extraction_path)[["article_id", "dataset_id", "family"]]
    custom_article_ids = set(hit_df[hit_df["family"] == "custom"]["article_id"].unique().tolist())

    if len(custom_article_ids) == 0:
        print("No custom articles found, skipping filter")
        hit_df.to_parquet(os.path.join(cfg.save_dir, "filtered_candidates.parquet"), index=False)
        return  # no need to filter non-custom

    input_df = input_df[input_df["article_id"].isin(custom_article_ids)].reset_index(drop=True)
    hit_df_custom = hit_df[hit_df["family"] == "custom"].reset_index(drop=True)
    hit_df_non_custom = hit_df[hit_df["family"] != "custom"].reset_index(drop=True)

    print(f"shape of hit_df_custom: {hit_df_custom.shape}")
    print(f"shape of hit_df_non_custom: {hit_df_non_custom.shape}")

    chunk_tokenizer = AutoTokenizer.from_pretrained(cfg.model_name)
    chunk_df = create_chunks(input_df, chunk_tokenizer, tokens_per_chunk=cfg.tokens_per_chunk, chunk_overlap=cfg.chunk_overlap)

    if cfg.xml_first:
        chunk_df = chunk_df.sort_values(by="source", ascending=False).reset_index(drop=True)  # Use XML if available

    # load candidate data
    gdf = hit_df_custom.groupby("article_id")["dataset_id"].agg(list).reset_index()
    article2hits = dict(zip(gdf["article_id"], gdf["dataset_id"]))

    chunk_df["candidate_ids"] = chunk_df.apply(lambda row: get_chunk_hits(row, article2hits), axis=1)
    candidate_df = chunk_df.explode("candidate_ids").dropna(subset=["candidate_ids"]).rename(columns={"candidate_ids": "dataset_id", "chunk": "context"})
    candidate_df = candidate_df.drop_duplicates(subset=["article_id", "dataset_id"], keep="first").reset_index(drop=True)
    candidate_df = candidate_df.sort_values(by="context").reset_index(drop=True)

    candidate_df = candidate_df[["article_id", "dataset_id", "context", "source"]]
    samp = candidate_df.sample().to_dict(orient="records")[0]
    print(json.dumps(samp))

    ds = Dataset.from_pandas(candidate_df)
    print(f"Number of examples: {len(ds)}")

    max_model_len = cfg.max_model_len

    llm = LLM(
        model=cfg.model_name,
        dtype="half",
        tensor_parallel_size=2,
        max_model_len=max_model_len,
        enforce_eager=True,
        gpu_memory_utilization=0.9,
        enable_prefix_caching=True,
        disable_log_stats=True,
        max_num_seqs=16,
        swap_space=0,
        cpu_offload_gb=0,
        max_num_batched_tokens=4096,
    )

    tokenizer = llm.get_tokenizer()

    index_df = pd.read_parquet(cfg.lookup_path)
    article2doi_online = get_doi_mapping(index_df)

    print("MODEL IS LOADED")

    # create prompts ---
    prompts = []
    print("CREATING PROMPTS...")
    for i, row in candidate_df.iterrows():
        article_id = row["article_id"]
        dataset_id = row["dataset_id"]
        context = row["context"]

        detected_dois = article2doi_online.get(article_id, "")  # Missing
        if len(detected_dois.strip()) == 0:
            detected_dois = "N/A"

        if (article_id in article2doi_online) and (cfg.use_online_doi):
            USER_TEMPLATE = USER_TEMPLATE_W_DOI
        else:
            USER_TEMPLATE = USER_TEMPLATE_WO_DOI

        user_prompt = USER_TEMPLATE.format(context=context, dataset_id=dataset_id, detected_dois=detected_dois)
        messages = [{"role": "system", "content": SYS_PROMPT}, {"role": "user", "content": user_prompt}]

        prompt = tokenizer.apply_chat_template(messages, add_generation_prompt=True, tokenize=False)

        # max len
        tokens = tokenizer.encode(prompt)
        token_length = len(tokens)
        extra_tokens = token_length - (max_model_len - 16)

        if extra_tokens > 0:
            print(f"Prompt length: {token_length} > {max_model_len} - 16")
            print(f"Prompt: {prompt}")
            print("-" * 100)
            prompt = tokenizer.decode(tokens[extra_tokens:])

        prompts.append(prompt)

    print("DONE CREATING PROMPTS")

    # print a few prompts
    if len(prompts) >=2:
        samples = random.sample(prompts, 2)
        for p in samples:
            print(p)
            print("-" * 100)

    print("RUNNING OUTPUT GEN")
    batch_size = 4096
    probs_list = []

    # Process in batches
    for i in range(0, len(prompts), batch_size):
        batch_prompts = prompts[i : i + batch_size]
        print(f"Processing batch {i // batch_size + 1}/{(len(prompts) + batch_size - 1) // batch_size} (items {i + 1}-{min(i + batch_size, len(prompts))})")

        # Generate outputs for this batch
        batch_outputs = llm.generate(batch_prompts, SamplingParams(temperature=0.0, skip_special_tokens=True, max_tokens=1, logprobs=20), use_tqdm=True)

        # Extract probabilities for this batch
        for output in batch_outputs:
            lps = output.outputs[0].logprobs[0]
            probs_list.append(get_yes_prob(lps))

    sub_df = pd.DataFrame()
    sub_df["article_id"] = candidate_df["article_id"]
    sub_df["dataset_id"] = candidate_df["dataset_id"]
    sub_df["yes_prob"] = probs_list
    sub_df = sub_df.sort_values(by="yes_prob", ascending=False).reset_index(drop=True)
    sub_df = sub_df.drop_duplicates(subset=["article_id", "dataset_id"], keep="first").reset_index(drop=True)

    oof_df = sub_df.copy()
    oof_df["should_keep"] = oof_df.apply(lambda x: filter_fn(cfg, x), axis=1)
    oof_df = oof_df[oof_df["should_keep"]].reset_index(drop=True)
    oof_df = oof_df.drop(columns=["should_keep"])
    oof_df = oof_df.drop_duplicates(subset=["article_id", "dataset_id"], keep="first").reset_index(drop=True)
    oof_df["family"] = "custom"
    oof_df = oof_df[["article_id", "dataset_id", "family"]].copy()

    # merge with non-custom
    print(f"shape before filter: {hit_df.shape}")
    oof_df = pd.concat([oof_df, hit_df_non_custom[["article_id", "dataset_id", "family"]]], ignore_index=True)
    oof_df = oof_df.drop_duplicates(subset=["article_id", "dataset_id"], keep="first").reset_index(drop=True)

    save_dir = cfg.save_dir
    os.makedirs(save_dir, exist_ok=True)

    oof_df.to_parquet(os.path.join(save_dir, "filtered_candidates.parquet"), index=False)
    print(f"shape after filter: {oof_df.shape}")


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--config_path", type=str, default="conf.yaml")
    args = parser.parse_args()

    cfg = OmegaConf.load(args.config_path)
    main(cfg)

    if torch.distributed.is_initialized():
        torch.distributed.destroy_process_group()

Writing filter_candidates.py

In [7]:
%%writefile config_filter.yaml

save_dir: ./working
extraction_path: ./working/candidates.parquet

doi_th: 0.3
acc_th: 0.1

tokens_per_chunk: 1296
chunk_overlap: 256

model_name: /kaggle/input/mdc_filter_qwen2b/transformers/default/1
max_model_len: 2048

xml_first: false
use_online_doi: true

lookup_path: ./working/doi_bank.parquet

Writing config_filter.yaml

In [8]:
%%time
!python filter_candidates.py --config_path config_filter.yaml

INFO 09-08 22:46:51 [__init__.py:244] Automatically detected platform cuda.
2025-09-08 22:46:51.852793: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:477] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1757371611.876643      92 cuda_dnn.cc:8310] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1757371611.884074      92 cuda_blas.cc:1418] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
Cache directory (cache/exp_tmp/txt) exists? -> True
# of previously processed files: 524
# of new files processed: 0
shape of hit_df_custom: (2, 3)
shape of hit_df_non_custom: (101, 3)
Processing 2 articles using 8 jobs...
Preparing parallel jobs:   0%|                            | 0/2 [00:00<?, ?it/s][Parallel(n_jobs=8)]: Using backend LokyBackend with 8 concurrent workers.
Preparing parallel jobs: 100%|███████████████████| 2/2 [00:00<00:00, 333.77it/s]
[Parallel(n_jobs=8)]: Done   2 out of   2 | elapsed:    4.3s finished
{"article_id": "10.1002_anie.202005531", "dataset_id": "ANIE202005531", "context": "BioC-API 20250509 collection.key PMC7540508 CC BY 10.1002/anie.202005531 PMC7540508 32463942 ANIE202005531 15918 37 arenes Pummerer reaction reaction mechanisms sulfoxides trifluoromethylthiolation This is an open access article under the terms of the http://creativecommons.org/licenses/by/4.0/ License, which permits use, distribution and reproduction in any medium, provided the original work is properly cited. 15922 surname:Wang;given-names:Dong;prefix:Dr. surname:Carlton;given-names:C. Grace surname:Tayu;given-names:Masanori;prefix:Dr. surname:McDouall;given-names:Joseph J. W.;prefix:Dr. surname:Perry;given-names:Gregory J. P.;prefix:Dr. surname:Procter;given-names:David J.;prefix:Prof.\u00e2\u0080\u0085Dr. \nD. Wang, C. G. Carlton, M. Tayu, J. J. W. McDouall, G. J. P. Perry, D. J. Procter, Angew. Chem. Int. Ed.\n2020, 59, 15918.\n TITLE front 59 2020 0 Trifluoromethyl Sulfoxides: Reagents for Metal\u00e2\u0080\u0090Free C\u00e2\u0088\u0092H Trifluoromethylthiolation ABSTRACT abstract_title_1 86 Abstract ABSTRACT abstract 95 Trifluoromethyl sulfoxides are a new class of trifluoromethylthiolating reagent. The sulfoxides engage in metal\u00e2\u0080\u0090free C\u00e2\u0088\u0092H trifluoromethylthiolation with a range of (hetero)arenes. The method is also applicable to the functionalization of important compound classes, such as ligand derivatives and polyaromatics, and in the late\u00e2\u0080\u0090stage trifluoromethylthiolation of medicines and agrochemicals. The isolation and characterization of a sulfonium salt intermediate supports an interrupted Pummerer reaction mechanism. ABSTRACT abstract 613  May I interrupt? Taking advantage of the interrupted Pummerer reaction, trifluoromethyl sulfoxides engage in the metal\u00e2\u0080\u0090free C\u00e2\u0088\u0092H trifluoromethylthiolation of (hetero)arenes, including drug molecules and natural products. This new class of trifluoromethylthiolating reagent exploits a new strategy for trifluoromethylthiolation in which sulfonium salts are assembled and selectively deconstructed.  INTRO paragraph 1015 Incorporating fluorine into organic compounds is a useful tool in drug design and development. The fluoro group is well known to improve the pharmacokinetic properties of a molecule and fluorine\u00e2\u0080\u009018 is an important radioisotope in molecular imaging.1, 2 Trifluoromethylthio (SCF3) groups are commonly found in drug molecules and veterinary medicines.3, 4 By combining a fluorinated moiety with a heteroatom, many have turned to the SCF3 group to impart useful properties, such as high lipophilicity, to a compound of interest.5  INTRO paragraph 1545 An attractive route for incorporating SCF3 groups into organic molecules is through the direct, metal\u00e2\u0080\u0090free functionalization of C\u00e2\u0088\u0092H bonds.6 Early methods using trifluoromethylsulfenyl chloride have fallen from favor because of concerns over handling and toxicity of the reagent.7 This triggered a push to develop shelf\u00e2\u0080\u0090stable, easy\u00e2\u0080\u0090to\u00e2\u0080\u0090handle trifluoromethylthiolating agents (Scheme\u00e2\u0080\u00851\u00e2\u0080\u0089A).8 Despite the advantages of these reagents, they are generally limited to the C\u00e2\u0088\u0092H trifluoromethylthiolation of highly electron\u00e2\u0080\u0090rich (hetero)arenes, such as indoles and phenols, whereas reactions involving less nucleophilic arenes, such as anisole and toluene, are scarce.8a, 8b, 8d, 8o, 8p Furthermore, few reports describe the use of these reagents for the late\u00e2\u0080\u0090stage trifluoromethylthiolation of complex molecules.8a, 8b, 8j, 8m, 8n  ANIE-59-15918-g001.jpg anie202005531-fig-5001 FIG fig_caption 2389 A)\u00e2\u0080\u0085Current methods for transition metal\u00e2\u0080\u0090free C\u00e2\u0088\u0092H trifluoromethylthiolation. B)\u00e2\u0080\u0085This work: C\u00e2\u0088\u0092H trifluoromethylthiolation by an interrupted Pummerer reaction. INTRO paragraph 2556 In recent years, our group9 and others10 have explored the so\u00e2\u0080\u0090called interrupted Pummerer reaction of sulfoxides and its use for the functionalization of C\u00e2\u0088\u0092H bonds.11 For example, we have described the thioarylation of simple arenes using sulfoxides as sulfide precursors.9c Key to these reactions is the in situ formation of a highly electrophilic sulfonium salt, by activation of the sulfoxide with an acid anhydride, which is susceptible to reaction with a range of nucleophiles. INTRO paragraph 3043 We were keen to assess whether underutilized trifluoromethyl sulfoxides would engage in C\u00e2\u0088\u0092H trifluoromethylthiolation. We reasoned that trifluoromethylsulfonium salts, generated from trifluoromethyl sul", "source": "xml"}
Number of examples: 2
INFO 09-08 22:47:17 [config.py:841] This model supports multiple tasks: {'reward', 'generate', 'classify', 'embed'}. Defaulting to 'generate'.
WARNING 09-08 22:47:17 [config.py:3371] Casting torch.bfloat16 to torch.float16.
INFO 09-08 22:47:17 [config.py:1472] Using max model len 2048
WARNING 09-08 22:47:17 [arg_utils.py:1735] Compute Capability < 8.0 is not supported by the V1 Engine. Falling back to V0.
WARNING 09-08 22:47:18 [cuda.py:102] To see benefits of async output processing, enable CUDA graph. Since, enforce-eager is enabled, async output processor cannot be used
INFO 09-08 22:47:18 [llm_engine.py:230] Initializing a V0 LLM engine (v0.9.2) with config: model='/kaggle/input/mdc_filter_qwen2b/transformers/default/1', speculative_config=None, tokenizer='/kaggle/input/mdc_filter_qwen2b/transformers/default/1', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, override_neuron_config={}, tokenizer_revision=None, trust_remote_code=False, dtype=torch.float16, max_seq_len=2048, download_dir=None, load_format=LoadFormat.AUTO, tensor_parallel_size=2, pipeline_parallel_size=1, disable_custom_all_reduce=False, quantization=None, enforce_eager=True, kv_cache_dtype=auto,  device_config=cuda, decoding_config=DecodingConfig(backend='auto', disable_fallback=False, disable_any_whitespace=False, disable_additional_properties=False, reasoning_backend=''), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None), seed=0, served_model_name=/kaggle/input/mdc_filter_qwen2b/transformers/default/1, num_scheduler_steps=1, multi_step_stream_outputs=True, enable_prefix_caching=True, chunked_prefill_enabled=False, use_async_output_proc=False, pooler_config=None, compilation_config={"level":0,"debug_dump_path":"","cache_dir":"","backend":"","custom_ops":[],"splitting_ops":[],"use_inductor":true,"compile_sizes":[],"inductor_compile_config":{"enable_auto_functionalized_v2":false},"inductor_passes":{},"use_cudagraph":true,"cudagraph_num_of_warmups":0,"cudagraph_capture_sizes":[],"cudagraph_copy_inputs":false,"full_cuda_graph":false,"max_capture_size":0,"local_cache_dir":null}, use_cached_outputs=False,
WARNING 09-08 22:47:19 [__init__.py:2662] We must use the `spawn` multiprocessing start method. Overriding VLLM_WORKER_MULTIPROC_METHOD to 'spawn'. See https://docs.vllm.ai/en/latest/usage/troubleshooting.html#python-multiprocessing for more information. Reason: CUDA is initialized
WARNING 09-08 22:47:19 [multiproc_worker_utils.py:307] Reducing Torch parallelism from 2 threads to 1 to avoid unnecessary CPU contention. Set OMP_NUM_THREADS in the external environment to tune this value as needed.
INFO 09-08 22:47:19 [cuda.py:311] Cannot use FlashAttention-2 backend for Volta and Turing GPUs.
INFO 09-08 22:47:19 [cuda.py:360] Using XFormers backend.
INFO 09-08 22:47:25 [__init__.py:244] Automatically detected platform cuda.
2025-09-08 22:47:25.731701: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:477] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1757371645.754179     149 cuda_dnn.cc:8310] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1757371645.760767     149 cuda_blas.cc:1418] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
(VllmWorkerProcess pid=149) INFO 09-08 22:47:31 [multiproc_worker_utils.py:226] Worker ready; awaiting tasks
(VllmWorkerProcess pid=149) INFO 09-08 22:47:31 [cuda.py:311] Cannot use FlashAttention-2 backend for Volta and Turing GPUs.
(VllmWorkerProcess pid=149) INFO 09-08 22:47:31 [cuda.py:360] Using XFormers backend.
[W908 22:47:42.116973295 socket.cpp:200] [c10d] The hostname of the client socket cannot be retrieved. err=-3
[W908 22:47:42.499920533 socket.cpp:200] [c10d] The hostname of the client socket cannot be retrieved. err=-3
[W908 22:47:52.127537617 socket.cpp:200] [c10d] The hostname of the client socket cannot be retrieved. err=-3
[W908 22:48:02.133060828 socket.cpp:200] [c10d] The hostname of the client socket cannot be retrieved. err=-3
INFO 09-08 22:48:02 [__init__.py:1152] Found nccl from library libnccl.so.2
(VllmWorkerProcess pid=149) INFO 09-08 22:48:02 [__init__.py:1152] Found nccl from library libnccl.so.2
(VllmWorkerProcess pid=149) INFO 09-08 22:48:02 [pynccl.py:70] vLLM is using nccl==2.26.2
INFO 09-08 22:48:02 [pynccl.py:70] vLLM is using nccl==2.26.2
INFO 09-08 22:48:02 [custom_all_reduce_utils.py:208] generating GPU P2P access cache in /root/.cache/vllm/gpu_p2p_access_cache_for_0,1.json
INFO 09-08 22:48:15 [custom_all_reduce_utils.py:246] reading GPU P2P access cache from /root/.cache/vllm/gpu_p2p_access_cache_for_0,1.json
(VllmWorkerProcess pid=149) INFO 09-08 22:48:15 [custom_all_reduce_utils.py:246] reading GPU P2P access cache from /root/.cache/vllm/gpu_p2p_access_cache_for_0,1.json
INFO 09-08 22:48:15 [shm_broadcast.py:289] vLLM message queue communication handle: Handle(local_reader_ranks=[1], buffer_handle=(1, 4194304, 6, 'psm_31365e1d'), local_subscribe_addr='ipc:///tmp/452449d5-2517-4596-a433-d955fbf35e2f', remote_subscribe_addr=None, remote_addr_ipv6=False)
INFO 09-08 22:48:15 [parallel_state.py:1076] rank 0 in world size 2 is assigned as DP rank 0, PP rank 0, TP rank 0, EP rank 0
(VllmWorkerProcess pid=149) INFO 09-08 22:48:15 [parallel_state.py:1076] rank 1 in world size 2 is assigned as DP rank 0, PP rank 0, TP rank 1, EP rank 1
INFO 09-08 22:48:15 [model_runner.py:1171] Starting to load model /kaggle/input/mdc_filter_qwen2b/transformers/default/1...
(VllmWorkerProcess pid=149) INFO 09-08 22:48:16 [model_runner.py:1171] Starting to load model /kaggle/input/mdc_filter_qwen2b/transformers/default/1...
Loading safetensors checkpoint shards:   0% Completed | 0/1 [00:00<?, ?it/s]
Loading safetensors checkpoint shards: 100% Completed | 1/1 [00:17<00:00, 17.16s/it]
Loading safetensors checkpoint shards: 100% Completed | 1/1 [00:17<00:00, 17.16s/it]

(VllmWorkerProcess pid=149) INFO 09-08 22:48:33 [default_loader.py:272] Loading weights took 16.79 seconds
INFO 09-08 22:48:33 [default_loader.py:272] Loading weights took 17.33 seconds
(VllmWorkerProcess pid=149) INFO 09-08 22:48:34 [model_runner.py:1203] Model loading took 1.4496 GiB and 16.990443 seconds
INFO 09-08 22:48:34 [model_runner.py:1203] Model loading took 1.4496 GiB and 17.513313 seconds


(VllmWorkerProcess pid=149) INFO 09-08 22:48:40 [worker.py:294] model weights take 1.45GiB; non_torch_memory takes 0.12GiB; PyTorch activation peak memory takes 0.17GiB; the rest of the memory reserved for KV Cache is 11.52GiB.


INFO 09-08 22:48:40 [worker.py:294] model weights take 1.45GiB; non_torch_memory takes 0.12GiB; PyTorch activation peak memory takes 0.17GiB; the rest of the memory reserved for KV Cache is 11.52GiB.
INFO 09-08 22:48:40 [executor_base.py:113] # cuda blocks: 53938, # CPU blocks: 0
INFO 09-08 22:48:40 [executor_base.py:118] Maximum concurrency for 2048 tokens per request: 421.39x
INFO 09-08 22:48:40 [llm_engine.py:428] init engine (profile, create kv cache, warmup model) took 6.37 seconds
MODEL IS LOADED
CREATING PROMPTS...
DONE CREATING PROMPTS
<|im_start|>system
You are an expert at identifying research data citations in scientific literature. You excel at identifying and cataloging data citations in academic papers.

Your task is to determine whether a given DOI or Accession ID represents a valid citation based on the provided text context. Focus on identifying genuine data citations, not just any mention of an identifier.<|im_end|>
<|im_start|>user
Text snippet: BioC-API 20250509 collection.key PMC7540508 CC BY 10.1002/anie.202005531 PMC7540508 32463942 ANIE202005531 15918 37 arenes Pummerer reaction reaction mechanisms sulfoxides trifluoromethylthiolation This is an open access article under the terms of the http://creativecommons.org/licenses/by/4.0/ License, which permits use, distribution and reproduction in any medium, provided the original work is properly cited. 15922 surname:Wang;given-names:Dong;prefix:Dr. surname:Carlton;given-names:C. Grace surname:Tayu;given-names:Masanori;prefix:Dr. surname:McDouall;given-names:Joseph J. W.;prefix:Dr. surname:Perry;given-names:Gregory J. P.;prefix:Dr. surname:Procter;given-names:David J.;prefix:Prof.âDr.
D. Wang, C. G. Carlton, M. Tayu, J. J. W. McDouall, G. J. P. Perry, D. J. Procter, Angew. Chem. Int. Ed.
2020, 59, 15918.
 TITLE front 59 2020 0 Trifluoromethyl Sulfoxides: Reagents for MetalâFree CâH Trifluoromethylthiolation ABSTRACT abstract_title_1 86 Abstract ABSTRACT abstract 95 Trifluoromethyl sulfoxides are a new class of trifluoromethylthiolating reagent. The sulfoxides engage in metalâfree CâH trifluoromethylthiolation with a range of (hetero)arenes. The method is also applicable to the functionalization of important compound classes, such as ligand derivatives and polyaromatics, and in the lateâstage trifluoromethylthiolation of medicines and agrochemicals. The isolation and characterization of a sulfonium salt intermediate supports an interrupted Pummerer reaction mechanism. ABSTRACT abstract 613  May I interrupt? Taking advantage of the interrupted Pummerer reaction, trifluoromethyl sulfoxides engage in the metalâfree CâH trifluoromethylthiolation of (hetero)arenes, including drug molecules and natural products. This new class of trifluoromethylthiolating reagent exploits a new strategy for trifluoromethylthiolation in which sulfonium salts are assembled and selectively deconstructed.  INTRO paragraph 1015 Incorporating fluorine into organic compounds is a useful tool in drug design and development. The fluoro group is well known to improve the pharmacokinetic properties of a molecule and fluorineâ18 is an important radioisotope in molecular imaging.1, 2 Trifluoromethylthio (SCF3) groups are commonly found in drug molecules and veterinary medicines.3, 4 By combining a fluorinated moiety with a heteroatom, many have turned to the SCF3 group to impart useful properties, such as high lipophilicity, to a compound of interest.5  INTRO paragraph 1545 An attractive route for incorporating SCF3 groups into organic molecules is through the direct, metalâfree functionalization of CâH bonds.6 Early methods using trifluoromethylsulfenyl chloride have fallen from favor because of concerns over handling and toxicity of the reagent.7 This triggered a push to develop shelfâstable, easyâtoâhandle trifluoromethylthiolating agents (Schemeâ1âA).8 Despite the advantages of these reagents, they are generally limited to the CâH trifluoromethylthiolation of highly electronârich (hetero)arenes, such as indoles and phenols, whereas reactions involving less nucleophilic arenes, such as anisole and toluene, are scarce.8a, 8b, 8d, 8o, 8p Furthermore, few reports describe the use of these reagents for the lateâstage trifluoromethylthiolation of complex molecules.8a, 8b, 8j, 8m, 8n  ANIE-59-15918-g001.jpg anie202005531-fig-5001 FIG fig_caption 2389 A)âCurrent methods for transition metalâfree CâH trifluoromethylthiolation. B)âThis work: CâH trifluoromethylthiolation by an interrupted Pummerer reaction. INTRO paragraph 2556 In recent years, our group9 and others10 have explored the soâcalled interrupted Pummerer reaction of sulfoxides and its use for the functionalization of CâH bonds.11 For example, we have described the thioarylation of simple arenes using sulfoxides as sulfide precursors.9c Key to these reactions is the in situ formation of a highly electrophilic sulfonium salt, by activation of the sulfoxide with an acid anhydride, which is susceptible to reaction with a range of nucleophiles. INTRO paragraph 3043 We were keen to assess whether underutilized trifluoromethyl sulfoxides would engage in CâH trifluoromethylthiolation. We reasoned that trifluoromethylsulfonium salts, generated from trifluoromethyl sul

Focus DOI/Accession ID: ANIE202005531

Is ANIE202005531 a valid research data citation in this text snippet?

Respond with only Yes or No<|im_end|>
<|im_start|>assistant

----------------------------------------------------------------------------------------------------
<|im_start|>system
You are an expert at identifying research data citations in scientific literature. You excel at identifying and cataloging data citations in academic papers.

Your task is to determine whether a given DOI or Accession ID represents a valid citation based on the provided text context. Focus on identifying genuine data citations, not just any mention of an identifier.<|im_end|>
<|im_start|>user
Text snippet: 14–18).
While non-aromatic solvents were found to be less suited (en-
tries 14, 15), the use of a lower amount of base resulted in a
slightly increased enantioselectivity of 91:9 (compare entries 16
Eur. J. Org. Chem. 2020, 5173–5177
www.eurjoc.org
© 2020 The Authors published by Wiley-VCH GmbH
5174
and 6). However, the yield was noticeable lower, and we found
that actually this reaction stalled after around 60 % conversion,
requiring addition of more base to proceed to completion.
When carrying out the reaction under more concentrated con-
ditions, the yield improved slightly, while the enantioselectivity
decreased (entry 17). This result is in line with our recent obser-
vations for the α-hydroxylation of compounds 1, where higher
dilution was beneficial for high enantioselectivities as well.[10]
Finally, lowering the catalyst loading to 5 mol-% resulted in a
slightly lower selectivity but in a noteworthy reduced yield.
Again, the reaction stalled after a while and addition of more

# Prepare for type prediction

In [9]:
%%writefile prep_type_inputs.py

import argparse
import sys

import pandas as pd
from omegaconf import OmegaConf

sys.path.insert(0, "/kaggle/input/mdc-utils-v02/code")
from utils.ingest_utils import check_presence, score_context, split_text  # type: ignore


def main(cfg):
    candidate_df = pd.read_parquet(cfg.extraction_path)
    input_df = pd.read_parquet(cfg.input_path)

    # Split Candidates --
    candidate_df_doi = candidate_df[candidate_df["dataset_id"].str.startswith("https://doi.org")].reset_index(drop=True)
    candidate_df_acc = candidate_df[~candidate_df["dataset_id"].str.startswith("https://doi.org")].reset_index(drop=True)

    articles_with_doi = set(candidate_df_doi["article_id"].tolist())
    remove_acc_articles = set()

    for aid in articles_with_doi:
        input_row = input_df[input_df["article_id"] == aid]
        pdf_text = input_row["pdf_text"].values[0]
        xml_text = input_row["xml_text"].values[0]
        pdf_chunks = split_text(pdf_text)
        xml_chunks = split_text(xml_text)
        all_chunks = pdf_chunks + xml_chunks

        # check chunks with doi
        curr_doi_list = candidate_df_doi[candidate_df_doi["article_id"] == aid]["dataset_id"].tolist()

        hit_chunks = []
        for chunk in all_chunks:
            if any([check_presence(chunk, d) for d in curr_doi_list]):
                hit_chunks.append(chunk)

        # check hit scores
        for chunk in hit_chunks:
            if score_context(chunk) >= 5.0:
                remove_acc_articles.add(aid)
                break

    # remove accessions
    print(f"shape of candidate_df_acc before removing accessions: {candidate_df_acc.shape}")
    candidate_df_acc["should_remove"] = candidate_df_acc["article_id"].apply(lambda x: x in remove_acc_articles)
    candidate_df_acc = candidate_df_acc[~candidate_df_acc["should_remove"]].reset_index(drop=True)
    candidate_df_acc = candidate_df_acc.drop(columns=["should_remove"])
    print(f"shape of candidate_df_acc after removing accessions: {candidate_df_acc.shape}")

    # candidates that needs type predictions
    base_df = pd.concat([candidate_df_doi, candidate_df_acc], ignore_index=True)
    base_df = base_df.drop_duplicates(subset=["article_id", "dataset_id"], keep="first").reset_index(drop=True)
    base_df.to_parquet("./working/base_pred_df.parquet")

    # assume type
    assume_secondary_list = set(["cath", "alphafold", "cellosaurus", "chembl", "dbgap", "igsr", "pfam", "reactome", "refseq"])
    candidate_df_acc_secondary = candidate_df_acc[candidate_df_acc["family"].isin(assume_secondary_list)].reset_index()
    candidate_df_acc_secondary["probs"] = [[0.0, 1.0, 0.0] for _ in range(len(candidate_df_acc_secondary))]
    candidate_df_acc_secondary["type"] = "Secondary"
    candidate_df_acc_secondary = candidate_df_acc_secondary[["article_id", "dataset_id", "probs", "type"]]
    candidate_df_acc_secondary.to_parquet("./working/acc_preds_assumed.parquet")

    # infer
    candidate_df_acc_infer = candidate_df_acc[~candidate_df_acc["family"].isin(assume_secondary_list)].reset_index(drop=True)
    print(f"shape of candidate_df_acc_infer before clipping: {candidate_df_acc_infer.shape}")

    # candidate_df_acc_infer = candidate_df_acc_infer.drop_duplicates(subset=["article_id", "dataset_id"], keep="first").groupby(["article_id", "family"], sort=False).head(cfg.max_acc_per_family).reset_index(drop=True)
    # candidate_df_acc_infer = candidate_df_acc_infer.drop_duplicates(subset=["article_id", "dataset_id"], keep="first").groupby(["article_id", "family"], sort=False, group_keys=False).apply(lambda grp: grp.sample(n=min(cfg.max_acc_per_family, len(grp)), random_state=42)).reset_index(drop=True)
    candidate_df_acc_infer = candidate_df_acc_infer.drop_duplicates(subset=["article_id", "dataset_id"], keep="first").sample(frac=1, random_state=42).groupby(["article_id", "family"], sort=False).head(cfg.max_acc_per_family).reset_index(drop=True)
    print(f"shape of candidate_df_acc_infer after clipping: {candidate_df_acc_infer.shape}")


    infer_df = pd.concat([candidate_df_acc_infer, candidate_df_doi], ignore_index=True)
    infer_df = infer_df.sort_values(by="article_id").reset_index(drop=True)
    infer_df.to_parquet("./working/candidates_infer.parquet")

    #---
    print(f"# of rows for inference: {len(infer_df)}")
    print(f"# of candidates: {len(base_df)}")


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--config_path", type=str, default="conf/pipeline.yaml")
    args = ap.parse_args()
    cfg = OmegaConf.load(args.config_path)
    main(cfg)

Writing prep_type_inputs.py

In [10]:
%%writefile config_prep.yaml

save_dir: ./working
extraction_path: ./working/filtered_candidates.parquet
input_path: ./working/inputs.parquet
max_acc_per_family: 8

Writing config_prep.yaml

In [11]:
!python prep_type_inputs.py --config_path config_prep.yaml

shape of candidate_df_acc before removing accessions: (48, 3)
shape of candidate_df_acc after removing accessions: (11, 3)
shape of candidate_df_acc_infer before clipping: (1, 3)
shape of candidate_df_acc_infer after clipping: (1, 3)
# of rows for inference: 54
# of candidates: 64

In [12]:
# infer_df = pd.read_parquet("./working/base_pred_df.parquet")
# candidate_df = pd.read_parquet("./working/candidates_infer.parquet")

# # # Split Candidates ---
# candidate_df_doi = candidate_df[candidate_df["dataset_id"].str.startswith("https://doi.org")].reset_index(drop=True)
# candidate_df_acc = candidate_df[~candidate_df["dataset_id"].str.startswith("https://doi.org")].reset_index(drop=True)

In [13]:
# infer_df.shape, candidate_df.shape, candidate_df_doi.shape, candidate_df_acc.shape

In [14]:
# candidate_df_doi

In [15]:
# candidate_df_acc = candidate_df_acc.drop_duplicates(subset=['article_id', 'dataset_id'])
# candidate_df_acc.shape

In [16]:
# candidate_df_doi = candidate_df_doi.drop_duplicates(subset=['article_id', 'dataset_id'])
# candidate_df_doi.shape

# Type Classification

In [17]:
%%writefile classify_candidates.py

import sys

sys.path.insert(0, "/kaggle/input/mdc-utils-v02/code")

import argparse
import os
import random
import re
from pathlib import Path

import numpy as np
import pandas as pd
import torch
import vllm
from omegaconf import OmegaConf
from pandarallel import pandarallel
from transformers import AutoTokenizer

code_dir = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, code_dir)

from utils.ingest_utils import _find_dataset_positions, check_presence, load_data, get_context, get_context_v2, get_context_many_accessions

SYS_PROMPT = """You are an expert at analyzing research data usage in academic papers. You will be shown a snippet of text likely containing one or more Accession IDs and/or DOIs.

Analyze the context to determine how a given Accession ID and/or DOI is being used:

A) PRIMARY - The authors generated this data for their current study
B) SECONDARY - The authors are using existing data from other sources
C) NONE - This is not a research data citation"""

USER_TEMPLATE = """# Context:\n\n{context}

# Focus DOI/Accession ID: **{dataset_id}**

# Task: Classify {dataset_id} as:
A) PRIMARY - Dataset created by these authors for this paper
B) SECONDARY - Dataset from previous work being reused
C) NONE - Not a dataset citation

Respond with only one letter: A, B, or C."""

os.environ["TOKENIZERS_PARALLELISM"] = "false"
pandarallel.initialize(progress_bar=True, nb_workers=4)


def get_probs(logprobs):
    a_logit = None
    b_logit = None
    c_logit = None

    for _, logprob_obj in logprobs.items():
        token_str = logprob_obj.decoded_token.strip().lower()

        if token_str == "a":
            if a_logit is None:
                a_logit = logprob_obj.logprob
        elif token_str == "b":
            if b_logit is None:
                b_logit = logprob_obj.logprob
        elif token_str == "c":
            if c_logit is None:
                c_logit = logprob_obj.logprob

    default_val = -20.0
    if a_logit is None:
        a_logit = default_val

    if b_logit is None:
        b_logit = default_val

    if c_logit is None:
        c_logit = default_val

    logits = np.array([a_logit, b_logit, c_logit])
    logits_max = np.max(logits)
    exp_logits = np.exp(logits - logits_max)
    normalized_scores = exp_logits / np.sum(exp_logits)

    return normalized_scores


def get_doi_mapping(index_df, input_df):
    gdf = index_df.groupby("article_id")["dataset_id"].agg(set).reset_index()
    article2dataset_online = dict(zip(gdf["article_id"], gdf["dataset_id"]))

    article_to_row = {row["article_id"]: row for _, row in input_df.iterrows()}

    article2doi_online = {}
    for article_id, dataset_ids in article2dataset_online.items():
        if article_id not in article_to_row:
            continue

        doi_candidates = [y for y in dataset_ids if y.startswith("https://doi.org")]

        row = article_to_row[article_id]
        filtered_dois = []

        for doi in doi_candidates:
            if check_presence(row["pdf_text"], doi) or check_presence(row["xml_text"], doi):
                filtered_dois.append(doi)
            article2doi_online[article_id] = filtered_dois

    return article2doi_online


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--config_path", type=str, default="conf/eval.yaml")
    args = parser.parse_args()

    cfg = OmegaConf.load(args.config_path)

    if os.getenv("KAGGLE_IS_COMPETITION_RERUN"):
        data_dir = Path("/kaggle/input/make-data-count-finding-data-references/test")
    else:
        data_dir = Path("/kaggle/input/make-data-count-finding-data-references/train")

    # ---
    cache_dir = Path("cache")
    cache_dir.mkdir(parents=True, exist_ok=True)

    input_df = load_data(data_dir, cache_dir)

    if not os.getenv("KAGGLE_IS_COMPETITION_RERUN"):
        input_df = input_df.sort_values(by="article_id").reset_index(drop=True)
        n_ex = int(os.getenv("N_EX"))
        input_df = input_df.head(n_ex)

    current_ids = set(input_df["article_id"].tolist())
    current_ids_lower = set(x.lower() for x in current_ids)
    chunk_tokenizer = AutoTokenizer.from_pretrained(cfg.model_name)

    # ---------
    candidate_df = pd.read_parquet(cfg.candidate_path) # article_id, dataset_id
    candidate_df = candidate_df.drop_duplicates(subset=["article_id", "dataset_id"], keep="first").reset_index(drop=True)
    candidate_df = candidate_df[["article_id", "dataset_id"]]
    print(f"shape of candidates: {candidate_df.shape}")

    # add the text fields ---
    data = []
    for _, row in input_df.iterrows():
        article_id = row["article_id"]
        pdf_text = row["pdf_text"]
        xml_text = row["xml_text"]

        data.append({"article_id": article_id, "text": pdf_text, "source": "pdf"})
        data.append({"article_id": article_id, "text": xml_text, "source": "xml"})

    text_df = pd.DataFrame(data)

    candidate_df = candidate_df.merge(text_df, on=["article_id"])
    candidate_df = candidate_df[["article_id", "dataset_id", "text", "source"]]

    # filter out rows for which dataset_id is not in the text
    print(f"shape before search for dataset_id in text: {candidate_df.shape}")
    candidate_df = candidate_df[candidate_df.apply(lambda row: check_presence(row["text"], row["dataset_id"]), axis=1)].reset_index(drop=True)
    print(f"shape after search for dataset_id in text: {candidate_df.shape}")
    if cfg.xml_first:
        candidate_df = candidate_df.sort_values(by="source", ascending=False).reset_index(drop=True)  # Use XML if available
            
    candidate_df = candidate_df.drop_duplicates(subset=["article_id", "dataset_id"], keep="first").reset_index(drop=True)
    print(f"shape after deduplication: {candidate_df.shape}")

    index_df = pd.read_parquet("./working/index.parquet")
    doi_map = get_doi_mapping(index_df, input_df)
    candidate_df["detected_dois"] = candidate_df["article_id"].map(lambda x: doi_map.get(x, []))

    ##########################################
    candidate_df_doi = candidate_df[candidate_df["dataset_id"].str.startswith("https://doi.org")].reset_index(drop=True)
    candidate_df_acc = candidate_df[~candidate_df["dataset_id"].str.startswith("https://doi.org")].reset_index(drop=True)
    
    base_df = pd.read_parquet("./working/base_pred_df.parquet") # article_id, dataset_id, family
    candidate_df_acc = candidate_df_acc.merge(base_df, on=['article_id', 'dataset_id'], how='left')
    candidate_df_acc['family'] = candidate_df_acc['family'].fillna('custom')
    
    count_df = candidate_df_acc.groupby(["article_id", "family"])["dataset_id"].agg(lambda x: len(set(x))).reset_index().rename(columns={"dataset_id": "count"})
    gdf = candidate_df_acc.groupby(["article_id", "family"])["dataset_id"].agg(list).reset_index().rename(columns={"dataset_id": "detected_accession_ids"})
    long_table_articles = set(count_df[count_df["count"] >= cfg.max_accession_ids_per_family]["article_id"].tolist())
    candidate_df_acc_long = candidate_df_acc[candidate_df_acc["article_id"].isin(long_table_articles)].reset_index(drop=True)
    candidate_df_acc_long_infer = candidate_df_acc_long
    candidate_df_acc_long_infer = candidate_df_acc_long_infer.merge(gdf, on=['article_id', 'family'], how='left')
    print(count_df)

    # print(candidate_df_acc_long_infer)
    candidate_df_acc_normal = candidate_df_acc[~candidate_df_acc["article_id"].isin(long_table_articles)].reset_index(drop=True)
    candidate_df_nornal_infer = pd.concat([candidate_df_doi, candidate_df_acc_normal]).reset_index(drop=True)

    # add context
    if cfg.use_v2_context:
        candidate_df_nornal_infer["context"] = candidate_df_nornal_infer.parallel_apply(lambda row: get_context_v2(cfg, row, chunk_tokenizer), axis=1)
    else:
        candidate_df_nornal_infer["context"] = candidate_df_nornal_infer.parallel_apply(lambda row: get_context(cfg, row, chunk_tokenizer), axis=1)

    if len(candidate_df_acc_long_infer) > 0:
        candidate_df_acc_long_infer["context"] = candidate_df_acc_long_infer.parallel_apply(lambda row: get_context_many_accessions(cfg, row, chunk_tokenizer), axis=1)
        candidate_df = pd.concat([candidate_df_nornal_infer, candidate_df_acc_long_infer]).reset_index(drop=True)
    else:
        candidate_df = candidate_df_nornal_infer.copy()
    
    ##########################################
    # candidate_df["context"] = candidate_df.parallel_apply(lambda row: get_context(cfg, row, chunk_tokenizer), axis=1)

    candidate_df = candidate_df.drop(columns=["text"])
    print(f"shape of candidate_df: {candidate_df.shape}")

    # Load LLM
    max_model_len = cfg.max_model_len
    model_path = cfg.model_name

    llm = vllm.LLM(
        model_path,
        tensor_parallel_size=torch.cuda.device_count(),
        quantization=cfg.quantization,
        gpu_memory_utilization=0.95,
        trust_remote_code=True,
        dtype="half",
        enforce_eager=True,
        max_model_len=max_model_len,
        disable_log_stats=True,
        enable_prefix_caching=True,
        cpu_offload_gb=cfg.cpu_offload_gb,
        max_num_seqs=cfg.max_num_seqs,
        swap_space=cfg.swap_space,
        max_num_batched_tokens=max_model_len,
    )

    tokenizer = llm.get_tokenizer()

    # create prompts ---
    prompts = []

    for i, row in candidate_df.iterrows():
        article_id = row["article_id"]
        dataset_id = row["dataset_id"]
        context = row["context"]

        user_prompt = USER_TEMPLATE.format(context=context, dataset_id=dataset_id)
        messages = [{"role": "system", "content": SYS_PROMPT}, {"role": "user", "content": user_prompt}]

        # ---
        prompt = tokenizer.apply_chat_template(messages, add_generation_prompt=True, tokenize=False)

        tokens = tokenizer.encode(prompt)
        token_length = len(tokens)
        extra_tokens = token_length - (max_model_len - 16)
        if extra_tokens > 0:
            prompt = tokenizer.decode(tokens[extra_tokens:])

        prompts.append(prompt)

    # show
    nprompt = min(2, len(prompts))
    show_prompts = random.sample(prompts, nprompt)
    for i, prompt in enumerate(show_prompts):
        print(f"Prompt {i}: {prompt}")
        print("-" * 100)

    # vllm
    outputs = llm.generate(prompts, vllm.SamplingParams(temperature=0.0, skip_special_tokens=True, max_tokens=1, logprobs=20), use_tqdm=True)

    probs_list = []
    for output in outputs:
        lps = output.outputs[0].logprobs[0]
        probs_list.append(get_probs(lps))

    sub_df = pd.DataFrame()
    sub_df["article_id"] = candidate_df["article_id"]
    sub_df["dataset_id"] = candidate_df["dataset_id"]
    sub_df["probs"] = probs_list

    sub_df = sub_df.groupby(["article_id", "dataset_id"])["probs"].apply(lambda x: np.mean(x, axis=0)).reset_index()
    choices = ["Primary", "Secondary", "NA"]
    sub_df["type"] = sub_df["probs"].apply(lambda x: choices[np.argmax(x)])

    # save --
    sub_df.to_parquet(os.path.join(cfg.save_dir, cfg.output_file))

Writing classify_candidates.py

In [18]:
%%writefile config_classify_14b.yaml

save_dir: ./working
output_file: preds_14b.parquet
candidate_path: ./working/candidates_infer.parquet

model_name: /kaggle/input/mdc_qwen14b_merged/transformers/default/14 # /kaggle/input/mdc_qwen14b_merged/transformers/default/9
max_model_len: 3600
cpu_offload_gb: 2
max_num_seqs: 1
quantization:
swap_space: 0

context:
  char_per_chunk: 1400
  char_overlap: 100
  top_k: 2
  max_hits: 5
  relevance_th: 8.0
  max_doi_chunk: 1
  token_budget: 3072

xml_first: false
use_v2_context: true # false
max_accession_ids_per_family: 8

Writing config_classify_14b.yaml

In [19]:
%%time
!python classify_candidates.py --config_path config_classify_14b.yaml

INFO: Pandarallel will run on 4 workers.
INFO: Pandarallel will use Memory file system to transfer data between the main process and workers.
Cache directory (cache/exp_tmp/txt) exists? -> True
# of previously processed files: 524
# of new files processed: 0
shape of candidates: (54, 2)
shape before search for dataset_id in text: (108, 4)
shape after search for dataset_id in text: (93, 4)
shape after deduplication: (54, 4)
                 article_id family  count
0  10.1021_acsomega.3c06074    pdb      1
   0.00%                                          |        0 /       14 |
   0.00%                                          |        0 /       14 |
   0.00%                                          |        0 /       13 |
   0.00%                                          |        0 /       13 |                          MMM   0.00%                                          |        0 /       14 |
   0.00%                                          |        0 /       14 |
   7.69% :::                                      |        1 /       13 |
   0.00%                                          |        0 /       13 |                          MMM   7.14% ::                                       |        1 /       14 |
   7.14% ::                                       |        1 /       14 |
  15.38% ::::::                                   |        2 /       13 |
   7.69% :::                                      |        1 /       13 |                          MMM  14.29% :::::                                    |        2 /       14 |
  14.29% :::::                                    |        2 /       14 |
  30.77% ::::::::::::                             |        4 /       13 |
  15.38% ::::::                                   |        2 /       13 |                          MMM  14.29% :::::                                    |        2 /       14 |
  21.43% ::::::::                                 |        3 /       14 |
  38.46% :::::::::::::::                          |        5 /       13 |
  30.77% ::::::::::::                             |        4 /       13 |                          MMM  21.43% ::::::::                                 |        3 /       14 |
  28.57% :::::::::::                              |        4 /       14 |
  46.15% ::::::::::::::::::                       |        6 /       13 |
  38.46% :::::::::::::::                          |        5 /       13 |                          MMM  35.71% ::::::::::::::                           |        5 /       14 |
  35.71% ::::::::::::::                           |        5 /       14 |
  46.15% ::::::::::::::::::                       |        6 /       13 |
  46.15% ::::::::::::::::::                       |        6 /       13 |                          MMM  35.71% ::::::::::::::                           |        5 /       14 |
  42.86% :::::::::::::::::                        |        6 /       14 |
  61.54% ::::::::::::::::::::::::                 |        8 /       13 |
  53.85% :::::::::::::::::::::                    |        7 /       13 |                          MMM  50.00% ::::::::::::::::::::                     |        7 /       14 |
  50.00% ::::::::::::::::::::                     |        7 /       14 |
  61.54% ::::::::::::::::::::::::                 |        8 /       13 |
  61.54% ::::::::::::::::::::::::                 |        8 /       13 |                          MMM  57.14% ::::::::::::::::::::::                   |        8 /       14 |
  57.14% ::::::::::::::::::::::                   |        8 /       14 |
  69.23% :::::::::::::::::::::::::::              |        9 /       13 |
  69.23% :::::::::::::::::::::::::::              |        9 /       13 |                          MMM  71.43% ::::::::::::::::::::::::::::             |       10 /       14 |
  64.29% :::::::::::::::::::::::::                |        9 /       14 |
  69.23% :::::::::::::::::::::::::::              |        9 /       13 |
  76.92% ::::::::::::::::::::::::::::::           |       10 /       13 |                          MMM  78.57% :::::::::::::::::::::::::::::::          |       11 /       14 |
  71.43% ::::::::::::::::::::::::::::             |       10 /       14 |
  76.92% ::::::::::::::::::::::::::::::           |       10 /       13 |
  84.62% :::::::::::::::::::::::::::::::::        |       11 /       13 |                          MMM  78.57% :::::::::::::::::::::::::::::::          |       11 /       14 |
  78.57% :::::::::::::::::::::::::::::::          |       11 /       14 |
  76.92% ::::::::::::::::::::::::::::::           |       10 /       13 |
 100.00% :::::::::::::::::::::::::::::::::::::::: |       13 /       13 |                          MMM  85.71% ::::::::::::::::::::::::::::::::::       |       12 /       14 |
  85.71% ::::::::::::::::::::::::::::::::::       |       12 /       14 |
  76.92% ::::::::::::::::::::::::::::::           |       10 /       13 |
 100.00% :::::::::::::::::::::::::::::::::::::::: |       13 /       13 |                          MMM  85.71% ::::::::::::::::::::::::::::::::::       |       12 /       14 |
 100.00% :::::::::::::::::::::::::::::::::::::::: |       14 /       14 |
  76.92% ::::::::::::::::::::::::::::::           |       10 /       13 |
 100.00% :::::::::::::::::::::::::::::::::::::::: |       13 /       13 |                          MMM 100.00% :::::::::::::::::::::::::::::::::::::::: |       14 /       14 |
 100.00% :::::::::::::::::::::::::::::::::::::::: |       14 /       14 |
  84.62% :::::::::::::::::::::::::::::::::        |       11 /       13 |
 100.00% :::::::::::::::::::::::::::::::::::::::: |       13 /       13 |                          MMM 100.00% :::::::::::::::::::::::::::::::::::::::: |       14 /       14 |
 100.00% :::::::::::::::::::::::::::::::::::::::: |       14 /       14 |
  92.31% ::::::::::::::::::::::::::::::::::::     |       12 /       13 |
 100.00% :::::::::::::::::::::::::::::::::::::::: |       13 /       13 |                          MMM 100.00% :::::::::::::::::::::::::::::::::::::::: |       14 /       14 |
 100.00% :::::::::::::::::::::::::::::::::::::::: |       14 /       14 |
 100.00% :::::::::::::::::::::::::::::::::::::::: |       13 /       13 |
 100.00% :::::::::::::::::::::::::::::::::::::::: |       13 /       13 |                          shape of candidate_df: (54, 6)
INFO 09-08 22:49:07 [__init__.py:244] Automatically detected platform cuda.
2025-09-08 22:49:07.722730: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:477] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1757371747.748669     330 cuda_dnn.cc:8310] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1757371747.754838     330 cuda_blas.cc:1418] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
INFO 09-08 22:49:25 [config.py:841] This model supports multiple tasks: {'generate', 'classify', 'embed', 'reward'}. Defaulting to 'generate'.
WARNING 09-08 22:49:25 [config.py:3371] Casting torch.bfloat16 to torch.float16.
INFO 09-08 22:49:25 [config.py:1472] Using max model len 3600
WARNING 09-08 22:49:25 [arg_utils.py:1735] Compute Capability < 8.0 is not supported by the V1 Engine. Falling back to V0.
WARNING 09-08 22:49:26 [cuda.py:102] To see benefits of async output processing, enable CUDA graph. Since, enforce-eager is enabled, async output processor cannot be used
INFO 09-08 22:49:26 [llm_engine.py:230] Initializing a V0 LLM engine (v0.9.2) with config: model='/kaggle/input/mdc_qwen14b_merged/transformers/default/14', speculative_config=None, tokenizer='/kaggle/input/mdc_qwen14b_merged/transformers/default/14', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, override_neuron_config={}, tokenizer_revision=None, trust_remote_code=True, dtype=torch.float16, max_seq_len=3600, download_dir=None, load_format=LoadFormat.AUTO, tensor_parallel_size=2, pipeline_parallel_size=1, disable_custom_all_reduce=False, quantization=None, enforce_eager=True, kv_cache_dtype=auto,  device_config=cuda, decoding_config=DecodingConfig(backend='auto', disable_fallback=False, disable_any_whitespace=False, disable_additional_properties=False, reasoning_backend=''), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None), seed=0, served_model_name=/kaggle/input/mdc_qwen14b_merged/transformers/default/14, num_scheduler_steps=1, multi_step_stream_outputs=True, enable_prefix_caching=True, chunked_prefill_enabled=False, use_async_output_proc=False, pooler_config=None, compilation_config={"level":0,"debug_dump_path":"","cache_dir":"","backend":"","custom_ops":[],"splitting_ops":[],"use_inductor":true,"compile_sizes":[],"inductor_compile_config":{"enable_auto_functionalized_v2":false},"inductor_passes":{},"use_cudagraph":true,"cudagraph_num_of_warmups":0,"cudagraph_capture_sizes":[],"cudagraph_copy_inputs":false,"full_cuda_graph":false,"max_capture_size":0,"local_cache_dir":null}, use_cached_outputs=False,
WARNING 09-08 22:49:26 [__init__.py:2662] We must use the `spawn` multiprocessing start method. Overriding VLLM_WORKER_MULTIPROC_METHOD to 'spawn'. See https://docs.vllm.ai/en/latest/usage/troubleshooting.html#python-multiprocessing for more information. Reason: CUDA is initialized
WARNING 09-08 22:49:26 [multiproc_worker_utils.py:307] Reducing Torch parallelism from 2 threads to 1 to avoid unnecessary CPU contention. Set OMP_NUM_THREADS in the external environment to tune this value as needed.
INFO 09-08 22:49:26 [cuda.py:311] Cannot use FlashAttention-2 backend for Volta and Turing GPUs.
INFO 09-08 22:49:26 [cuda.py:360] Using XFormers backend.
INFO: Pandarallel will run on 4 workers.
INFO: Pandarallel will use Memory file system to transfer data between the main process and workers.
INFO 09-08 22:49:32 [__init__.py:244] Automatically detected platform cuda.
2025-09-08 22:49:33.005137: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:477] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1757371773.028097     400 cuda_dnn.cc:8310] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1757371773.035034     400 cuda_blas.cc:1418] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
(VllmWorkerProcess pid=400) INFO 09-08 22:49:36 [multiproc_worker_utils.py:226] Worker ready; awaiting tasks
(VllmWorkerProcess pid=400) INFO 09-08 22:49:37 [cuda.py:311] Cannot use FlashAttention-2 backend for Volta and Turing GPUs.
(VllmWorkerProcess pid=400) INFO 09-08 22:49:37 [cuda.py:360] Using XFormers backend.
[W908 22:49:48.539068105 socket.cpp:200] [c10d] The hostname of the client socket cannot be retrieved. err=-3
[W908 22:49:48.908851795 socket.cpp:200] [c10d] The hostname of the client socket cannot be retrieved. err=-3
[W908 22:49:58.549816557 socket.cpp:200] [c10d] The hostname of the client socket cannot be retrieved. err=-3
[W908 22:50:08.560291303 socket.cpp:200] [c10d] The hostname of the client socket cannot be retrieved. err=-3
(VllmWorkerProcess pid=400) INFO 09-08 22:50:08 [__init__.py:1152] Found nccl from library libnccl.so.2
INFO 09-08 22:50:08 [__init__.py:1152] Found nccl from library libnccl.so.2
(VllmWorkerProcess pid=400) INFO 09-08 22:50:08 [pynccl.py:70] vLLM is using nccl==2.26.2
INFO 09-08 22:50:08 [pynccl.py:70] vLLM is using nccl==2.26.2
INFO 09-08 22:50:08 [custom_all_reduce_utils.py:246] reading GPU P2P access cache from /root/.cache/vllm/gpu_p2p_access_cache_for_0,1.json
(VllmWorkerProcess pid=400) INFO 09-08 22:50:08 [custom_all_reduce_utils.py:246] reading GPU P2P access cache from /root/.cache/vllm/gpu_p2p_access_cache_for_0,1.json
INFO 09-08 22:50:08 [shm_broadcast.py:289] vLLM message queue communication handle: Handle(local_reader_ranks=[1], buffer_handle=(1, 4194304, 6, 'psm_0e95009a'), local_subscribe_addr='ipc:///tmp/f0c3af06-573e-4c53-8f3b-973465b34e9a', remote_subscribe_addr=None, remote_addr_ipv6=False)
INFO 09-08 22:50:08 [parallel_state.py:1076] rank 0 in world size 2 is assigned as DP rank 0, PP rank 0, TP rank 0, EP rank 0
(VllmWorkerProcess pid=400) INFO 09-08 22:50:08 [parallel_state.py:1076] rank 1 in world size 2 is assigned as DP rank 0, PP rank 0, TP rank 1, EP rank 1
INFO 09-08 22:50:08 [model_runner.py:1171] Starting to load model /kaggle/input/mdc_qwen14b_merged/transformers/default/14...
(VllmWorkerProcess pid=400) INFO 09-08 22:50:08 [model_runner.py:1171] Starting to load model /kaggle/input/mdc_qwen14b_merged/transformers/default/14...
Loading safetensors checkpoint shards:   0% Completed | 0/6 [00:00<?, ?it/s]
Loading safetensors checkpoint shards:  17% Completed | 1/6 [00:23<01:59, 23.87s/it]
Loading safetensors checkpoint shards:  33% Completed | 2/6 [00:53<01:49, 27.46s/it]
Loading safetensors checkpoint shards:  50% Completed | 3/6 [01:20<01:21, 27.10s/it]
Loading safetensors checkpoint shards:  67% Completed | 4/6 [01:51<00:57, 28.72s/it]
Loading safetensors checkpoint shards:  83% Completed | 5/6 [02:31<00:32, 32.82s/it]
Loading safetensors checkpoint shards: 100% Completed | 6/6 [03:05<00:00, 33.27s/it]
Loading safetensors checkpoint shards: 100% Completed | 6/6 [03:05<00:00, 30.99s/it]

(VllmWorkerProcess pid=400) INFO 09-08 22:53:19 [default_loader.py:272] Loading weights took 186.20 seconds
INFO 09-08 22:53:19 [default_loader.py:272] Loading weights took 186.12 seconds
(VllmWorkerProcess pid=400) INFO 09-08 22:53:20 [model_runner.py:1203] Model loading took 11.8694 GiB and 190.296389 seconds
INFO 09-08 22:53:20 [model_runner.py:1203] Model loading took 11.8694 GiB and 190.311722 seconds


(VllmWorkerProcess pid=400) INFO 09-08 22:53:27 [worker.py:294] model weights take 11.87GiB; non_torch_memory takes 0.13GiB; PyTorch activation peak memory takes 0.58GiB; the rest of the memory reserved for KV Cache is 1.42GiB.


INFO 09-08 22:53:27 [worker.py:294] model weights take 11.87GiB; non_torch_memory takes 0.13GiB; PyTorch activation peak memory takes 0.58GiB; the rest of the memory reserved for KV Cache is 1.42GiB.
INFO 09-08 22:53:28 [executor_base.py:113] # cuda blocks: 968, # CPU blocks: 0
INFO 09-08 22:53:28 [executor_base.py:118] Maximum concurrency for 3600 tokens per request: 4.30x
INFO 09-08 22:53:28 [llm_engine.py:428] init engine (profile, create kv cache, warmup model) took 7.73 seconds
Prompt 0: <|im_start|>system
You are an expert at analyzing research data usage in academic papers. You will be shown a snippet of text likely containing one or more Accession IDs and/or DOIs.

Analyze the context to determine how a given Accession ID and/or DOI is being used:

A) PRIMARY - The authors generated this data for their current study
B) SECONDARY - The authors are using existing data from other sources
C) NONE - This is not a research data citation<|im_end|>
<|im_start|>user
# Context:

[Section 1]
Vol.:(0123456789)
1 3
Climate Dynamics (2023) 60:1729–1749
https://doi.org/10.1007/s00382-022-06361-7
Winter wet–dry weather patterns driving atmospheric rivers
and Santa Ana winds provide evidence for increasing wildfire hazard
in California
Kristen Guirguis1   · Alexander Gershunov1 · Benjamin Hatchett2 · Tamara Shulgina1 · Michael J. DeFlorio1 ·
Aneesh C. Subramanian3 · Janin Guzman‐Morales1 · Rosana Aguilera1 · Rachel Clemesha1 · Thomas W. Corringham1 ·
Luca Delle Monache1 · David Reynolds3 · Alex Tardy4 · Ivory Small4 · F. Martin Ralph1
Received: 7 September 2021 / Accepted: 25 May 2022 / Published online: 17 July 2022
© The Author(s) 2022
Abstract
Floods caused by atmospheric rivers and wildfires fanned by Santa Ana winds are common occurrences in California with
devastating societal impacts. In this work, we show that winter weather variability in California, including the occurrence
of extreme and impactful events, is linked to four atmospheric circulation regimes over the North Pacific Ocean previously
named and identified as the “NP4 modes”. These modes come in and out of phase with each other during the season, result-
ing in distinct weather patterns that recur throughout the historical record. Some phase combinations favor atmospheric
river landfalls and extreme daily or multi-day precipitation, while other phase combinations favor anomalously hot weather

[Section 2]
Summit snow course
has a long (1913–2021) and complete record.
2.7  Wildfire
Wildfire information is from the California Fire Protection's
Fire and Resource Assessment Program (FRAP) fire perim-
eters database (https://frap.fire.ca.gov/frap-projects/fire-
perimeters/). We focus on fire start dates for historical wild-
fires with burn sizes exceeding 1000 acres in the Southern
California (SoCal) counties of Santa Barbara, Ventura, Los
Angeles, Orange, Riverside, San Bernardino, and San Diego.
Our sample includes 76 wildfires spanning 1949–2018, with
most occurring in November (n = 40) or December (n = 21).
As mentioned above, most wildfires in California occur in
October, which is outside of our extended winter focus sea-
son. However, the wildfire season can and does extend into
winter during drought years or when delayed rains extend
dry vegetation into the peak of SAW season.
2.8  North Pacific atmospheric circulation regimes
We use daily amplitudes of four North Pacific atmospheric
circulation regimes (NP4 modes), which were identified
and shown to be essential drivers of vapor transport and
AR activity along the coast of western North America by
Guirguis et al. (2018, hereinafter GGR’18) and GGR’20.
These four modes are named according to their geographic
1733
Winter wet–dry weather patterns driving atmospheric rivers and Santa Ana winds provide evidence...
1 3
centers of action: Baja-Pacific (BP), Alaskan-Pacific (AP),

# 32B Model

In [20]:
%%writefile prep_difficult.py

import argparse
import pandas as pd

def get_uncertain_samples(oof_df, frac=0.2):
    oof_df = oof_df.copy()

    oof_df["null_p"] = oof_df["probs"].apply(lambda x: x[2])
    oof_df = oof_df[oof_df["null_p"] < 0.9].reset_index(drop=True)
    oof_df["diff"] = oof_df["probs"].apply(lambda x: abs(x[1] - x[0]))

    n_samples = int(len(oof_df) * frac)
    n_samples = max(1, n_samples)
    
    uncertain_df = oof_df.sort_values(by="diff").head(n_samples).reset_index(drop=True)
    uncertain_df = uncertain_df.drop(columns=["diff", "null_p"])

    return uncertain_df


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--input_path", type=str)
    ap.add_argument("--output_path", type=str)
    ap.add_argument("--frac_doi", type=float, default=0.5)
    ap.add_argument("--frac_acc", type=float, default=0.1)

    args = ap.parse_args()

    pred_df = pd.read_parquet(args.input_path)
    print(f"shape of input: {pred_df.shape}")
    pred_df_doi = pred_df[pred_df['dataset_id'].str.startswith("https://doi.org/")].reset_index(drop=True)
    pred_df_acc = pred_df[~pred_df['dataset_id'].str.startswith("https://doi.org/")].reset_index(drop=True)

    uncertain_df_doi = get_uncertain_samples(pred_df_doi, args.frac_doi)
    uncertain_df_acc = get_uncertain_samples(pred_df_acc, args.frac_acc)
    
    uncertain_df = pd.concat([uncertain_df_doi, uncertain_df_acc]).reset_index(drop=True)
    
    uncertain_df.to_parquet(args.output_path)
    print(f"shape of output: {uncertain_df.shape}")

Writing prep_difficult.py

In [21]:
!python prep_difficult.py --input_path ./working/preds_14b.parquet --output_path ./working/infer_uncertain_32b.parquet --frac_doi 0.5 --frac_acc 0.2

shape of input: (54, 4)
shape of output: (27, 4)

In [22]:
# df = pd.read_parquet("./working/infer_uncertain_32b.parquet")
# df.groupby(['article_id', 'dataset_id'])['type'].agg('count').reset_index()

In [23]:
%%writefile config_classify_32b.yaml

save_dir: ./working
output_file: preds_32b.parquet
candidate_path: ./working/infer_uncertain_32b.parquet

model_name: /kaggle/input/mdc_cls_qwen_32b_awq/transformers/default/2
max_model_len: 3600
cpu_offload_gb: 2
max_num_seqs: 1
quantization: awq
swap_space: 0

context:
  char_per_chunk: 1400
  char_overlap: 100
  top_k: 2
  max_hits: 5
  relevance_th: 8.0
  max_doi_chunk: 1
  token_budget: 3072

xml_first: true
use_v2_context: false
max_accession_ids_per_family: 8

Writing config_classify_32b.yaml

In [24]:
%%time
!python classify_candidates.py --config_path config_classify_32b.yaml

INFO: Pandarallel will run on 4 workers.
INFO: Pandarallel will use Memory file system to transfer data between the main process and workers.
Cache directory (cache/exp_tmp/txt) exists? -> True
# of previously processed files: 524
# of new files processed: 0
shape of candidates: (27, 2)
shape before search for dataset_id in text: (54, 4)
shape after search for dataset_id in text: (45, 4)
shape after deduplication: (27, 4)
                 article_id family  count
0  10.1021_acsomega.3c06074    pdb      1
   0.00%                                          |        0 /        7 |
   0.00%                                          |        0 /        7 |
   0.00%                                          |        0 /        7 |
   0.00%                                          |        0 /        6 |                          MMM   0.00%                                          |        0 /        7 |
  14.29% :::::                                    |        1 /        7 |
   0.00%                                          |        0 /        7 |
   0.00%                                          |        0 /        6 |                          MMM  14.29% :::::                                    |        1 /        7 |
  14.29% :::::                                    |        1 /        7 |
  14.29% :::::                                    |        1 /        7 |
  33.33% :::::::::::::                            |        2 /        6 |                          MMM  28.57% :::::::::::                              |        2 /        7 |
  42.86% :::::::::::::::::                        |        3 /        7 |
  28.57% :::::::::::                              |        2 /        7 |
  33.33% :::::::::::::                            |        2 /        6 |                          MMM  42.86% :::::::::::::::::                        |        3 /        7 |
  57.14% ::::::::::::::::::::::                   |        4 /        7 |
  42.86% :::::::::::::::::                        |        3 /        7 |
  50.00% ::::::::::::::::::::                     |        3 /        6 |                          MMM  57.14% ::::::::::::::::::::::                   |        4 /        7 |
  71.43% ::::::::::::::::::::::::::::             |        5 /        7 |
  42.86% :::::::::::::::::                        |        3 /        7 |
  83.33% :::::::::::::::::::::::::::::::::        |        5 /        6 |                          MMM  57.14% ::::::::::::::::::::::                   |        4 /        7 |
  71.43% ::::::::::::::::::::::::::::             |        5 /        7 |
  57.14% ::::::::::::::::::::::                   |        4 /        7 |
 100.00% :::::::::::::::::::::::::::::::::::::::: |        6 /        6 |                          MMM  71.43% ::::::::::::::::::::::::::::             |        5 /        7 |
  85.71% ::::::::::::::::::::::::::::::::::       |        6 /        7 |
  71.43% ::::::::::::::::::::::::::::             |        5 /        7 |
 100.00% :::::::::::::::::::::::::::::::::::::::: |        6 /        6 |                          MMM  71.43% ::::::::::::::::::::::::::::             |        5 /        7 |
 100.00% :::::::::::::::::::::::::::::::::::::::: |        7 /        7 |
  71.43% ::::::::::::::::::::::::::::             |        5 /        7 |
 100.00% :::::::::::::::::::::::::::::::::::::::: |        6 /        6 |                          MMM 100.00% :::::::::::::::::::::::::::::::::::::::: |        7 /        7 |
 100.00% :::::::::::::::::::::::::::::::::::::::: |        7 /        7 |
  85.71% ::::::::::::::::::::::::::::::::::       |        6 /        7 |
 100.00% :::::::::::::::::::::::::::::::::::::::: |        6 /        6 |                          MMM 100.00% :::::::::::::::::::::::::::::::::::::::: |        7 /        7 |
 100.00% :::::::::::::::::::::::::::::::::::::::: |        7 /        7 |
 100.00% :::::::::::::::::::::::::::::::::::::::: |        7 /        7 |
 100.00% :::::::::::::::::::::::::::::::::::::::: |        6 /        6 |                          shape of candidate_df: (27, 6)
INFO 09-08 22:55:57 [__init__.py:244] Automatically detected platform cuda.
2025-09-08 22:55:58.311081: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:477] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1757372158.337953     544 cuda_dnn.cc:8310] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1757372158.344206     544 cuda_blas.cc:1418] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
INFO 09-08 22:56:17 [config.py:841] This model supports multiple tasks: {'embed', 'classify', 'reward', 'generate'}. Defaulting to 'generate'.
WARNING 09-08 22:56:17 [config.py:3371] Casting torch.bfloat16 to torch.float16.
INFO 09-08 22:56:17 [config.py:1472] Using max model len 3600
WARNING 09-08 22:56:17 [config.py:960] awq quantization is not fully optimized yet. The speed can be slower than non-quantized models.
WARNING 09-08 22:56:17 [arg_utils.py:1735] Compute Capability < 8.0 is not supported by the V1 Engine. Falling back to V0.
WARNING 09-08 22:56:17 [cuda.py:102] To see benefits of async output processing, enable CUDA graph. Since, enforce-eager is enabled, async output processor cannot be used
INFO 09-08 22:56:17 [llm_engine.py:230] Initializing a V0 LLM engine (v0.9.2) with config: model='/kaggle/input/mdc_cls_qwen_32b_awq/transformers/default/2', speculative_config=None, tokenizer='/kaggle/input/mdc_cls_qwen_32b_awq/transformers/default/2', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, override_neuron_config={}, tokenizer_revision=None, trust_remote_code=True, dtype=torch.float16, max_seq_len=3600, download_dir=None, load_format=LoadFormat.AUTO, tensor_parallel_size=2, pipeline_parallel_size=1, disable_custom_all_reduce=False, quantization=awq, enforce_eager=True, kv_cache_dtype=auto,  device_config=cuda, decoding_config=DecodingConfig(backend='auto', disable_fallback=False, disable_any_whitespace=False, disable_additional_properties=False, reasoning_backend=''), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None), seed=0, served_model_name=/kaggle/input/mdc_cls_qwen_32b_awq/transformers/default/2, num_scheduler_steps=1, multi_step_stream_outputs=True, enable_prefix_caching=True, chunked_prefill_enabled=False, use_async_output_proc=False, pooler_config=None, compilation_config={"level":0,"debug_dump_path":"","cache_dir":"","backend":"","custom_ops":[],"splitting_ops":[],"use_inductor":true,"compile_sizes":[],"inductor_compile_config":{"enable_auto_functionalized_v2":false},"inductor_passes":{},"use_cudagraph":true,"cudagraph_num_of_warmups":0,"cudagraph_capture_sizes":[],"cudagraph_copy_inputs":false,"full_cuda_graph":false,"max_capture_size":0,"local_cache_dir":null}, use_cached_outputs=False,
WARNING 09-08 22:56:18 [__init__.py:2662] We must use the `spawn` multiprocessing start method. Overriding VLLM_WORKER_MULTIPROC_METHOD to 'spawn'. See https://docs.vllm.ai/en/latest/usage/troubleshooting.html#python-multiprocessing for more information. Reason: CUDA is initialized
WARNING 09-08 22:56:18 [multiproc_worker_utils.py:307] Reducing Torch parallelism from 2 threads to 1 to avoid unnecessary CPU contention. Set OMP_NUM_THREADS in the external environment to tune this value as needed.
INFO 09-08 22:56:18 [cuda.py:311] Cannot use FlashAttention-2 backend for Volta and Turing GPUs.
INFO 09-08 22:56:18 [cuda.py:360] Using XFormers backend.
INFO: Pandarallel will run on 4 workers.
INFO: Pandarallel will use Memory file system to transfer data between the main process and workers.
INFO 09-08 22:56:24 [__init__.py:244] Automatically detected platform cuda.
2025-09-08 22:56:24.540633: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:477] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1757372184.564295     614 cuda_dnn.cc:8310] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1757372184.571404     614 cuda_blas.cc:1418] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
(VllmWorkerProcess pid=614) INFO 09-08 22:56:29 [multiproc_worker_utils.py:226] Worker ready; awaiting tasks
(VllmWorkerProcess pid=614) INFO 09-08 22:56:29 [cuda.py:311] Cannot use FlashAttention-2 backend for Volta and Turing GPUs.
(VllmWorkerProcess pid=614) INFO 09-08 22:56:29 [cuda.py:360] Using XFormers backend.
[W908 22:56:40.213881805 socket.cpp:200] [c10d] The hostname of the client socket cannot be retrieved. err=-3
[W908 22:56:40.578302328 socket.cpp:200] [c10d] The hostname of the client socket cannot be retrieved. err=-3
[W908 22:56:50.224540011 socket.cpp:200] [c10d] The hostname of the client socket cannot be retrieved. err=-3
[W908 22:57:00.234995520 socket.cpp:200] [c10d] The hostname of the client socket cannot be retrieved. err=-3
INFO 09-08 22:57:00 [__init__.py:1152] Found nccl from library libnccl.so.2
(VllmWorkerProcess pid=614) INFO 09-08 22:57:00 [__init__.py:1152] Found nccl from library libnccl.so.2
INFO 09-08 22:57:00 [pynccl.py:70] vLLM is using nccl==2.26.2
(VllmWorkerProcess pid=614) INFO 09-08 22:57:00 [pynccl.py:70] vLLM is using nccl==2.26.2
INFO 09-08 22:57:00 [custom_all_reduce_utils.py:246] reading GPU P2P access cache from /root/.cache/vllm/gpu_p2p_access_cache_for_0,1.json
(VllmWorkerProcess pid=614) INFO 09-08 22:57:00 [custom_all_reduce_utils.py:246] reading GPU P2P access cache from /root/.cache/vllm/gpu_p2p_access_cache_for_0,1.json
INFO 09-08 22:57:00 [shm_broadcast.py:289] vLLM message queue communication handle: Handle(local_reader_ranks=[1], buffer_handle=(1, 4194304, 6, 'psm_90a6e5cc'), local_subscribe_addr='ipc:///tmp/0ea45e7d-f45d-4a30-8867-194d309ef9c0', remote_subscribe_addr=None, remote_addr_ipv6=False)
INFO 09-08 22:57:00 [parallel_state.py:1076] rank 0 in world size 2 is assigned as DP rank 0, PP rank 0, TP rank 0, EP rank 0
(VllmWorkerProcess pid=614) INFO 09-08 22:57:00 [parallel_state.py:1076] rank 1 in world size 2 is assigned as DP rank 0, PP rank 0, TP rank 1, EP rank 1
INFO 09-08 22:57:00 [model_runner.py:1171] Starting to load model /kaggle/input/mdc_cls_qwen_32b_awq/transformers/default/2...
(VllmWorkerProcess pid=614) INFO 09-08 22:57:01 [model_runner.py:1171] Starting to load model /kaggle/input/mdc_cls_qwen_32b_awq/transformers/default/2...
Loading safetensors checkpoint shards:   0% Completed | 0/4 [00:00<?, ?it/s]
Loading safetensors checkpoint shards:  25% Completed | 1/4 [00:41<02:05, 41.67s/it]
Loading safetensors checkpoint shards:  50% Completed | 2/4 [01:15<01:14, 37.07s/it]
Loading safetensors checkpoint shards:  75% Completed | 3/4 [01:46<00:34, 34.37s/it]
Loading safetensors checkpoint shards: 100% Completed | 4/4 [02:27<00:00, 36.78s/it]
Loading safetensors checkpoint shards: 100% Completed | 4/4 [02:27<00:00, 36.79s/it]

(VllmWorkerProcess pid=614) INFO 09-08 22:59:31 [default_loader.py:272] Loading weights took 146.89 seconds
INFO 09-08 22:59:31 [default_loader.py:272] Loading weights took 147.60 seconds
(VllmWorkerProcess pid=614) INFO 09-08 22:59:32 [model_runner.py:1203] Model loading took 7.0882 GiB and 150.482438 seconds
INFO 09-08 22:59:33 [model_runner.py:1203] Model loading took 7.0882 GiB and 151.188138 seconds


(VllmWorkerProcess pid=614) INFO 09-08 22:59:48 [worker.py:294] model weights take 7.09GiB; non_torch_memory takes 0.13GiB; PyTorch activation peak memory takes 0.68GiB; the rest of the memory reserved for KV Cache is 6.10GiB.


INFO 09-08 22:59:48 [worker.py:294] model weights take 7.09GiB; non_torch_memory takes 0.13GiB; PyTorch activation peak memory takes 0.68GiB; the rest of the memory reserved for KV Cache is 6.10GiB.
INFO 09-08 22:59:49 [executor_base.py:113] # cuda blocks: 3123, # CPU blocks: 0
INFO 09-08 22:59:49 [executor_base.py:118] Maximum concurrency for 3600 tokens per request: 13.88x
INFO 09-08 22:59:49 [llm_engine.py:428] init engine (profile, create kv cache, warmup model) took 16.04 seconds
Prompt 0: <|im_start|>system
You are an expert at analyzing research data usage in academic papers. You will be shown a snippet of text likely containing one or more Accession IDs and/or DOIs.

Analyze the context to determine how a given Accession ID and/or DOI is being used:

A) PRIMARY - The authors generated this data for their current study
B) SECONDARY - The authors are using existing data from other sources
C) NONE - This is not a research data citation<|im_end|>
<|im_start|>user
# Context:

[Section 1]
Med Phys Med Phys 10.1002/(ISSN)2473-4209 MP Medical Physics 0094-2405 2473-4209 John Wiley and Sons Inc. Hoboken 7722027 32749075 10.1002/mp.14424 MP14424 Medical Physics Dataset Article Medical Physics Dataset Articles PleThora: Pleural effusion and thoracic cavity segmentations in diseased lungs for benchmarking chest CT processing pipelines PleThora Kiser  et al . Kiser Kendall J.
 1

 2

 3
 Kendall.j.kiser@uth.tmc.edu Ahmed Sara
 3
 Stieb Sonja
 3
 Mohamed Abdallah S. R.
 3

 4
 Elhalawani Hesham
 5
 Park Peter Y. S.
 6
 Doyle Nathan S.
 6
 Wang Brandon J.
 6
 Barman Arko
 2
 Li Zhao
 2
 Zheng W. Jim
 2
 Fuller Clifton D.
 3

 4
 cdfuller@mdanderson.org Giancardo Luca
 2

 5
 Luca.Giancardo@uth.tmc.edu
 1
 John P. and Kathrine G. McGovern Medical School
 Houston
 TX
 USA

 2
 Center for Precision Health
 UTHealth School of Biomedical Informatics
 Houston
 TX
 USA

 3
 Department of Radiation Oncology
 University of Texas MD Anderson Cancer Center
 Houston
 TX
 USA

 4
 MD Anderson Cancer Center‐UTHealth Graduate School of Biomedical Sciences
 Houston
 TX
 USA

 5
 Department of Radiation Oncology
 Cleveland Clinic Taussig Cancer Center
 Cleveland
 OH
 USA

 6
 Department of Diagnostic and Interventional Imaging
 John P. and Kathrine G. McGovern Medical School
 Houston
 TX
 USA
 *
Authors to whom

[Section 2]
son
 E
 ,
 Straus
 CM
 ,
 Armato
 SG
 3rd
 .  Deep convolutional neural networks for the automated segmentation of malignant pleural mesothelioma on computed tomography scans .  J Med Imaging (Bellingham) .  2018 ; 5 : 034503 . 30840717 13

 Park
 B
 ,
 Park
 H
 ,
 Lee
 SM
 ,
 Seo
 JB
 ,
 Kim
 N
 .  Lung segmentation on HRCT and volumetric CT for diffuse interstitial lung disease using deep convolutional neural networks .  J Digit Imaging .  2019 ; 32 : 1019 – 1026 . 31396776 14

 Chen
 G
 ,
 Xiang
 D
 ,
 Zhang
 B
 , et al.  Automatic pathological lung segmentation in low‐dose CT image using Eigenspace sparse shape composition .  IEEE Trans Med Imaging .  2019 ; 38 : 1736 – 1749 . 30605097 15

 Soliman
 A
 ,
 Khalifa
 F
 ,
 Elnakib
 A
 , et al.  Accurate lungs segmentation on CT chest images by adaptive appearance‐guided shape modeling .  IEEE Trans Med Imaging .  2017 ; 36 : 263 – 276 . 27705854 16

 Doel
 T
 ,
 Gavaghan
 DJ
 ,
 Grau
 V
 .  Review of automatic pulmonary lobe segmentation methods from CT .  Comput Med Imaging Graph .  2015 ; 40 : 13 – 29 . 25467805 17

 Ren
 H
 ,
 Zhou
 L
 ,
 Liu
 G
 , et al.  An unsupervised semi‐automated pulmonary nodule segmentation method based on enhanced region growing .  Quant Imaging Med Surg .  2020 ; 10 : 233 – 242 . 31956545 18

 Dong
 J
 ,
 Lu
 K
 ,
 Dai
 S
 ,
 Xue
 J
 ,
 Zhai
 R
 .  Auto‐Segmentation of Pathological Lung Parenchyma Based on Region Growing Method . Paper presented at: Internet Multimedia Computing and Service; Aug. 23–25, 2017; Qingdao, China.  10.1007/978-981-10-8530-7_23
 19

 Hofmanninger
 J
 ,
 Prayer
 F
 ,
 Pan
 J
 ,
 Rohrich
 S
 ,
 Prosch
 H
 ,
 Langs
 G
 .  Automatic lung segmentation in routine imaging is a data diversity problem, not a methodology problem . arXiv:2001.11767. Published 31 Jan  2020 . Accessed 4 Apr 2020. 20

 Shaukat
 F
 ,
 Raja
 G
 ,
 Frangi
 AF
 .  Computer‐aided detection of lung nodules: a review .  J Med Imaging .  2019 ; 6 : 1 . 21

 Clark
 K
 ,
 Vendt
 B
 ,
 Smith
 K
 , et al.  The cancer imaging archive (TCIA): maintaining and operating a public information repository .  J Digit Imaging .  2013 ; 26 : 1045 – 1057 . 23884657 22

 Aerts
 HJWL
 ,
 Wee
 L
 ,
 Rios Velazquez
 E
 , et al.  Data from NSCLC‐Radiomics [Dataset] . In:  The Cancer Imaging Archive ;  2019
 <b><focus> 10.7937/K9/TCIA.2015.PF0M9REI </focus></b>
 23

 Aerts
 HJ
 ,
 Velazquez
 ER
 ,
 Leijenaar
 RT
 , et al.  Decoding tumour phenotype by noninvasive imaging using a quantitative radiomics approach .  Nat Commun .  2014 ; 5 : 4006 . 24892406 24

 Li
 X
 ,
 Morgan
 PS
 ,
 Ashburner
 J
 ,
 Smith
 J
 ,
 Rorden
 C
 .  dcm2niix.exe [computer program] . Version v1.0.201811142020. Accessed January 23, 2019. Available from:  https://www.nitrc.org/plugins/mwiki/index.php/dcm2nii:MainPage
 25

 Li
 X
 ,
 Morgan
 PS
 ,
 Ashburner
 J
 ,
 Smith
 J
 ,
 Rorden
 C
 .  The first step for neuroimaging data analysis: DICOM to NIfTI conversion .  J Neurosci Methods .  2016 ; 264 : 47 – 56 . 26945974 26

 Pesiuk
 V
 .  Lung Segmentation (3D) [computer program] . GitHub 2017. Accessed December 15, 2018. Available from  https://github.com/imlab‐uiip/lung‐segmentation‐3d
 27

 Yushkevich
 PA
 ,
 Piven
 J
 ,
 Hazlett
 HC
 , et al.  User‐guided 3D active contour segmentation of anatomical structures: significantly improved efficiency and reliability .  Neuroimage .  2006 ; 31 : 1116 – 1128 . 16545965 28

 Panchal
 A
 .  Dicompyler [computer program] . Version vol 0.4.22014. Accessed February 4, 2020. Available from  https://www.dicompyler.com/
 29

 Oliphant
 TE
 .  Python for scientific computing .  Comput Sci Eng .  2007 ; 9 : 10 – 20 . 30

 Abraham
 A
 ,
 Pedregosa
 F
 ,
 Eickenberg
 M
 , et al.  Machine learning for neuroimaging with scikit‐learn .  Front Neuroinf

# Focus DOI/Accession ID: **https://doi.org/10.7937/k9/tcia.2015.pf0m9rei**

# Task: Classify https://doi.org/10.7937/k9/tcia.2015.pf0m9rei as:
A) PRIMARY - Dataset created by these authors for this paper
B) SECONDARY - Dataset from previous work being reused
C) NONE - Not a dataset citation

Respond with only one letter: A, B, or C.<|im_end|>
<|im_start|>assistant

----------------------------------------------------------------------------------------------------
Prompt 1: <|im_start|>system
You are an expert at analyzing research data usage in academic papers. You will be shown a snippet of text likely containing one or more Accession IDs and/or DOIs.

Analyze the context to determine how a given Accession ID and/or DOI is being used:


# 72b Model

In [25]:
!python prep_difficult.py --input_path ./working/preds_32b.parquet --output_path ./working/infer_uncertain_72b.parquet --frac_doi 0.1 --frac_acc 0.1

shape of input: (27, 4)
shape of output: (3, 4)

In [26]:
%%writefile config_classify_72b.yaml

save_dir: ./working
output_file: preds_72b.parquet
candidate_path: ./working/infer_uncertain_72b.parquet

model_name: /kaggle/input/mdc_cls_qwen_72b_awq/transformers/default/2 # /kaggle/input/mdc_cls_qwen_72b_awq/transformers/default/1
max_model_len: 2560
cpu_offload_gb: 8
max_num_seqs: 1
quantization: awq
swap_space: 1

context:
  char_per_chunk: 1200
  char_overlap: 100
  top_k: 0
  max_hits: 3
  relevance_th: 5.0
  max_doi_chunk: 1
  token_budget: 2048

xml_first: false
use_v2_context: false
max_accession_ids_per_family: 8

Writing config_classify_72b.yaml

In [27]:
%%time
!python classify_candidates.py --config_path config_classify_72b.yaml

INFO: Pandarallel will run on 4 workers.
INFO: Pandarallel will use Memory file system to transfer data between the main process and workers.
Cache directory (cache/exp_tmp/txt) exists? -> True
# of previously processed files: 524
# of new files processed: 0
shape of candidates: (3, 2)
shape before search for dataset_id in text: (6, 4)
shape after search for dataset_id in text: (6, 4)
shape after deduplication: (3, 4)
                 article_id family  count
0  10.1021_acsomega.3c06074    pdb      1
   0.00%                                          |        0 /        1 |
   0.00%                                          |        0 /        1 |
   0.00%                                          |        0 /        1 |                          MM   0.00%                                          |        0 /        1 |
 100.00% :::::::::::::::::::::::::::::::::::::::: |        1 /        1 |
   0.00%                                          |        0 /        1 |                          MM   0.00%                                          |        0 /        1 |
 100.00% :::::::::::::::::::::::::::::::::::::::: |        1 /        1 |
 100.00% :::::::::::::::::::::::::::::::::::::::: |        1 /        1 |                          MM 100.00% :::::::::::::::::::::::::::::::::::::::: |        1 /        1 |
 100.00% :::::::::::::::::::::::::::::::::::::::: |        1 /        1 |
 100.00% :::::::::::::::::::::::::::::::::::::::: |        1 /        1 |                          shape of candidate_df: (3, 6)
INFO 09-08 23:02:26 [__init__.py:244] Automatically detected platform cuda.
2025-09-08 23:02:27.053211: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:477] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1757372547.083303     733 cuda_dnn.cc:8310] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1757372547.091151     733 cuda_blas.cc:1418] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
INFO 09-08 23:02:47 [config.py:841] This model supports multiple tasks: {'generate', 'classify', 'reward', 'embed'}. Defaulting to 'generate'.
WARNING 09-08 23:02:47 [config.py:3371] Casting torch.bfloat16 to torch.float16.
INFO 09-08 23:02:47 [config.py:1472] Using max model len 2560
WARNING 09-08 23:02:47 [config.py:960] awq quantization is not fully optimized yet. The speed can be slower than non-quantized models.
WARNING 09-08 23:02:47 [arg_utils.py:1735] Compute Capability < 8.0 is not supported by the V1 Engine. Falling back to V0.
WARNING 09-08 23:02:47 [cuda.py:102] To see benefits of async output processing, enable CUDA graph. Since, enforce-eager is enabled, async output processor cannot be used
INFO 09-08 23:02:47 [llm_engine.py:230] Initializing a V0 LLM engine (v0.9.2) with config: model='/kaggle/input/mdc_cls_qwen_72b_awq/transformers/default/2', speculative_config=None, tokenizer='/kaggle/input/mdc_cls_qwen_72b_awq/transformers/default/2', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, override_neuron_config={}, tokenizer_revision=None, trust_remote_code=True, dtype=torch.float16, max_seq_len=2560, download_dir=None, load_format=LoadFormat.AUTO, tensor_parallel_size=2, pipeline_parallel_size=1, disable_custom_all_reduce=False, quantization=awq, enforce_eager=True, kv_cache_dtype=auto,  device_config=cuda, decoding_config=DecodingConfig(backend='auto', disable_fallback=False, disable_any_whitespace=False, disable_additional_properties=False, reasoning_backend=''), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None), seed=0, served_model_name=/kaggle/input/mdc_cls_qwen_72b_awq/transformers/default/2, num_scheduler_steps=1, multi_step_stream_outputs=True, enable_prefix_caching=True, chunked_prefill_enabled=False, use_async_output_proc=False, pooler_config=None, compilation_config={"level":0,"debug_dump_path":"","cache_dir":"","backend":"","custom_ops":[],"splitting_ops":[],"use_inductor":true,"compile_sizes":[],"inductor_compile_config":{"enable_auto_functionalized_v2":false},"inductor_passes":{},"use_cudagraph":true,"cudagraph_num_of_warmups":0,"cudagraph_capture_sizes":[],"cudagraph_copy_inputs":false,"full_cuda_graph":false,"max_capture_size":0,"local_cache_dir":null}, use_cached_outputs=False,
WARNING 09-08 23:02:48 [__init__.py:2662] We must use the `spawn` multiprocessing start method. Overriding VLLM_WORKER_MULTIPROC_METHOD to 'spawn'. See https://docs.vllm.ai/en/latest/usage/troubleshooting.html#python-multiprocessing for more information. Reason: CUDA is initialized
WARNING 09-08 23:02:48 [multiproc_worker_utils.py:307] Reducing Torch parallelism from 2 threads to 1 to avoid unnecessary CPU contention. Set OMP_NUM_THREADS in the external environment to tune this value as needed.
INFO 09-08 23:02:48 [cuda.py:311] Cannot use FlashAttention-2 backend for Volta and Turing GPUs.
INFO 09-08 23:02:48 [cuda.py:360] Using XFormers backend.
INFO: Pandarallel will run on 4 workers.
INFO: Pandarallel will use Memory file system to transfer data between the main process and workers.
INFO 09-08 23:02:54 [__init__.py:244] Automatically detected platform cuda.
2025-09-08 23:02:54.795879: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:477] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1757372574.819320     797 cuda_dnn.cc:8310] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1757372574.826297     797 cuda_blas.cc:1418] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
(VllmWorkerProcess pid=797) INFO 09-08 23:02:59 [multiproc_worker_utils.py:226] Worker ready; awaiting tasks
(VllmWorkerProcess pid=797) INFO 09-08 23:02:59 [cuda.py:311] Cannot use FlashAttention-2 backend for Volta and Turing GPUs.
(VllmWorkerProcess pid=797) INFO 09-08 23:02:59 [cuda.py:360] Using XFormers backend.
[W908 23:03:10.552447290 socket.cpp:200] [c10d] The hostname of the client socket cannot be retrieved. err=-3
[W908 23:03:10.923894833 socket.cpp:200] [c10d] The hostname of the client socket cannot be retrieved. err=-3
[W908 23:03:20.563339753 socket.cpp:200] [c10d] The hostname of the client socket cannot be retrieved. err=-3
[W908 23:03:30.573822826 socket.cpp:200] [c10d] The hostname of the client socket cannot be retrieved. err=-3
INFO 09-08 23:03:30 [__init__.py:1152] Found nccl from library libnccl.so.2
(VllmWorkerProcess pid=797) INFO 09-08 23:03:30 [__init__.py:1152] Found nccl from library libnccl.so.2
INFO 09-08 23:03:30 [pynccl.py:70] vLLM is using nccl==2.26.2
(VllmWorkerProcess pid=797) INFO 09-08 23:03:30 [pynccl.py:70] vLLM is using nccl==2.26.2
(VllmWorkerProcess pid=797) INFO 09-08 23:03:30 [custom_all_reduce_utils.py:246] reading GPU P2P access cache from /root/.cache/vllm/gpu_p2p_access_cache_for_0,1.json
INFO 09-08 23:03:30 [custom_all_reduce_utils.py:246] reading GPU P2P access cache from /root/.cache/vllm/gpu_p2p_access_cache_for_0,1.json
INFO 09-08 23:03:30 [shm_broadcast.py:289] vLLM message queue communication handle: Handle(local_reader_ranks=[1], buffer_handle=(1, 4194304, 6, 'psm_f3dbd663'), local_subscribe_addr='ipc:///tmp/b619424b-7dd9-40ce-983b-3f3d16fb53bf', remote_subscribe_addr=None, remote_addr_ipv6=False)
INFO 09-08 23:03:31 [parallel_state.py:1076] rank 0 in world size 2 is assigned as DP rank 0, PP rank 0, TP rank 0, EP rank 0
(VllmWorkerProcess pid=797) INFO 09-08 23:03:31 [parallel_state.py:1076] rank 1 in world size 2 is assigned as DP rank 0, PP rank 0, TP rank 1, EP rank 1
INFO 09-08 23:03:31 [model_runner.py:1171] Starting to load model /kaggle/input/mdc_cls_qwen_72b_awq/transformers/default/2...
(VllmWorkerProcess pid=797) INFO 09-08 23:03:31 [model_runner.py:1171] Starting to load model /kaggle/input/mdc_cls_qwen_72b_awq/transformers/default/2...
Loading safetensors checkpoint shards:   0% Completed | 0/9 [00:00<?, ?it/s]
Loading safetensors checkpoint shards:  11% Completed | 1/9 [00:44<05:59, 44.88s/it]
Loading safetensors checkpoint shards:  22% Completed | 2/9 [01:25<04:54, 42.14s/it]
Loading safetensors checkpoint shards:  33% Completed | 3/9 [01:55<03:40, 36.80s/it]
Loading safetensors checkpoint shards:  44% Completed | 4/9 [02:39<03:18, 39.71s/it]
Loading safetensors checkpoint shards:  56% Completed | 5/9 [02:54<02:03, 30.80s/it]
Loading safetensors checkpoint shards:  67% Completed | 6/9 [03:37<01:44, 34.79s/it]
Loading safetensors checkpoint shards:  78% Completed | 7/9 [04:14<01:11, 35.54s/it]
Loading safetensors checkpoint shards:  89% Completed | 8/9 [04:56<00:37, 37.51s/it]
Loading safetensors checkpoint shards: 100% Completed | 9/9 [05:37<00:00, 38.74s/it]
Loading safetensors checkpoint shards: 100% Completed | 9/9 [05:37<00:00, 37.50s/it]

(VllmWorkerProcess pid=797) INFO 09-08 23:09:18 [default_loader.py:272] Loading weights took 337.13 seconds
INFO 09-08 23:09:19 [default_loader.py:272] Loading weights took 337.82 seconds
(VllmWorkerProcess pid=797) INFO 09-08 23:09:22 [model_runner.py:1203] Model loading took 11.9424 GiB and 349.365098 seconds
INFO 09-08 23:09:22 [model_runner.py:1203] Model loading took 11.9424 GiB and 349.858092 seconds


(VllmWorkerProcess pid=797) INFO 09-08 23:09:43 [worker.py:294] model weights take 11.94GiB; non_torch_memory takes 0.14GiB; PyTorch activation peak memory takes 0.94GiB; the rest of the memory reserved for KV Cache is 0.98GiB.


INFO 09-08 23:09:43 [worker.py:294] model weights take 11.94GiB; non_torch_memory takes 0.14GiB; PyTorch activation peak memory takes 0.94GiB; the rest of the memory reserved for KV Cache is 0.98GiB.
INFO 09-08 23:09:43 [executor_base.py:113] # cuda blocks: 401, # CPU blocks: 409
INFO 09-08 23:09:43 [executor_base.py:118] Maximum concurrency for 2560 tokens per request: 2.51x
INFO 09-08 23:09:45 [llm_engine.py:428] init engine (profile, create kv cache, warmup model) took 23.53 seconds
Prompt 0: <|im_start|>system
You are an expert at analyzing research data usage in academic papers. You will be shown a snippet of text likely containing one or more Accession IDs and/or DOIs.

Analyze the context to determine how a given Accession ID and/or DOI is being used:

A) PRIMARY - The authors generated this data for their current study
B) SECONDARY - The authors are using existing data from other sources
C) NONE - This is not a research data citation<|im_end|>
<|im_start|>user
# Context:

[Section 1]
Identification of Oxidation State +1 in a Molecular Uranium
Complex
Luciano Barluzzi, Sean R. Giblin, Akseli Mansikkamäki,* and Richard A. Layfield*
Cite This: J. Am. Chem. Soc. 2022, 144, 18229−18233
Read Online
ACCESS
Metrics & More
Article Recommendations
*
sı
Supporting Information
ABSTRACT: The concept of oxidation state plays a fundamentally important role in defining the chemistry of the elements. In the f
block of the periodic table, well-known oxidation states in compounds of the lanthanides include 0, +2, +3 and +4, and oxidation
states for the actinides range from +7 to +2. Oxidation state +1 is conspicuous by its absence from the f-block elements. Here we
show that the uranium(II) metallocene [U(η5-C5
iPr5)2] and the uranium(III) metallocene [IU(η5-C5
iPr5)2] can be reduced by
potassium graphite in the presence of 2.2.2-cryptand to the uranium(I) metallocene [U(η5-C5
iPr5)2]−(1) (C5
iPr5 =
pentaisopropylcyclopentadienyl) as the salt of [K(2.2.2-cryptand)]+. An X-ray crystallographic study revealed that 1 has a bent
metallocene structure, and theoretical studies and magnetic measurements confirmed that the electronic ground state of uranium(I)
adopts a 5f3(7s/6dz
2)1(6dx

[Section 2]
.2.2-crypt)][1] would behave
toward azobenzene, N2Ph2. Adding 1 equiv of azobenzene to
[K(2.2.2-crypt)][1] in benzene caused a color change from
brown to green and precipitation of a dark-brown solid
(Scheme 1). 1H NMR spectroscopy revealed the formation of
[U(η5-C5
iPr5)2] (Figures S19 and S20), suggesting that a one-
electron transfer process had occurred. The precipitate was
identified by X-ray crystallography and IR and EPR spectros-
copies to be the azobenzene radical anion [N2Ph2]−as the salt
of [K(2.2.2-crypt)]+ (Table S1 and Figures S21−S24). This
one-electron reduction process contrasts to that shown by the
uranium(II) complex [U{N(SiMe3)2}3]−toward azobenzene,
which initiates a four-electron reduction and cleavage of the
nitrogen−nitrogen double bond in the substrate.30 This
reactivity, combined with the disproportionation of [K(2.2.2-
crypt)][1] into its uranium(II) precursor and uranium metal,
points to unexpected stability of [U(η5-C5
iPr5)2], most likely
due to the stabilizing effect of the bulky ligands.
In conclusion, we have shown that a metallocene of uranium
in the oxidation state +1 can be synthesized by reduction of
uranium(II) and uranium(III) precursors. Reactivity studies,
magnetic and spectroscopic measurements, and a DFT study
are consistent with the presence of uranium(I) with a 5f3(7s/
6dz
2)1(6dx
2−y
2 /6dxy)1 ground-state electron configuration. The
broader significance of [K(2.2.2-crypt)][1] is that soluble
molecular compounds of other actinides and some lanthanides
in the oxidation state +1 should also be viable targets. The
synthesis of a much larger family of compounds containing
lanthanide(I) and actinide(I) centers introduces new possibil-
ities for designing molecular magnets and luminescent
materials and for developing new f-element reactivity.
■ASSOCIATED CONTENT
Data Availability Statement
Additional research data supporting this publication are
available at <b><focus> 10.25377/sussex.21184705 </focus></b>.
*
sı Supporting Information
The Supporting Information is available free of charge at
https://pubs.acs.org/doi/10.1021/jacs.2c06519.
Synthesis, spectroscopic characterization, crystallo-
graphic details, magnetic property measurements, and
computational details (PDF)
Accession Codes
CCDC 2169273 and 2170255 contain the supplementary
crystallographic data for this paper. These data can be obtained
free of charge via www.ccdc.cam.ac.uk/data_request/cif, or by
emailing data_request@ccdc.cam.ac.uk, or by contacting The
Cambridge Crystallographic Data Centre, 12 Union Road,
Cambridge CB2 1EZ, U.K.; fax: +44 1223 336033.
■AUTHOR INFORMATION
Corresponding Authors
Akseli Mansikkamäki −NMR Research Group, University of
Oulu, FI-90014 Oulu, Finland;
orcid.org/0000-0003-
0401-4373; Email: akseli.mansikkamaki@oulu.fi
Richard A. Layfield −Department of Chemistry, School of Life
Sciences, University of Sussex, Brighton BN1 9JQ, U.K.;
orcid.org/0000-0002-6020-0309; Email: r.layfield@
sussex.ac.uk
Authors
Luciano Barluzzi −Department of Chemistry, School of Life
Sciences, University of Sussex, Brighton BN1 9JQ, U.K.;
orcid.org/0000-0001-6682-342X
Sean R. Giblin −School of Physics and Astronomy, Cardiff
University, Cardiff CF24 3AA, U.K.
Complete contact information is available at:
https://pubs.acs.org/10.1021/jacs.2c06519
Notes
The authors declare no competing financial interest.
■ACKNOWLEDGMENTS
The authors thank the EPSRC (Grants EP

# Focus DOI/Accession ID: **https://doi.org/10.25377/sussex.21184705**

# Task: Classify https://doi.org/10.25377/sussex.21184705 as:
A) PRIMARY - Dataset created by these authors for this paper
B) SECONDARY - Dataset from previous work being reused
C) NONE - Not a dataset citation

Respond with only one letter: A, B, or C.<|im_end|>
<|im_start|>assistant

----------------------------------------------------------------------------------------------------
Prompt 1: <|im_start|>system
You are an expert at analyzing research data usage in academic papers. You will be shown a snippet of text likely containing one or more Accession IDs and/or DOIs.

Analyze the context to determine how a given Accession ID and/or DOI is being used:

A) PRIMARY - The authors generated this data for their current study
B) SECONDARY - The authors are using existing data from other sources
C) NONE - This is not a research data citation<|im_end|>
<|im_start|>user
# Context:

[Section 1]
calculations were
conducted between sets with the same number of other heteroatoms, while observing the
variations in the specific heteroatom's count within the structure. To determine significant
effects, the number of other heteroatoms was kept constant, and the impact of a particular
heteroatom count was examined. If a substantial effect of at least around one log unit was
detected between the median pIC50 values of the compared sets, the compound with the
highest pIC50 was selected from the set with the higher median value, while the compound
with the lowest pIC50 was chosen from the set with the lowest median value.

.
CC-BY-NC-ND 4.0 International license
made available under a
(which was not certified by peer review) is the author/funder, who has granted bioRxiv a license to display the preprint in perpetuity. It is
The copyright holder for this preprint
this version posted August 7, 2023.
;
https://doi.org/10.1101/2023.08.05.552121
doi:
bioRxiv preprint

6
2.4 Ligand Preparation
The LigPrep module of Maestro molecular modeling package was employed to prepare the
508 ligands. During the ligand preparation process, the protonation states of the compounds
were calculated within a pH range of 7.0 ± 2.0 using the Epik module. Compounds with chiral
centers generated up to four distinct stereoisomers, and ionization states were considered for
each molecule. To ensure accurate representation of molecular characteristics, the OPLS3e
force field was applied.
2.5
Protein preparation
The cryo-EM structure of the hERG K+ channel (PDB ID: <b><focus> 5VA1 </focus></b>) was obtained from the
RCSB Protein Data Bank [12]. In this structure, the channel is in an open-like state, and the
voltage sensors exhibit a depolarized shape. Despite its relatively small size, the central cavity
contains four deep hydrophobic pockets, which may explain the heightened sensitivity of the
hERG channel to diverse ligand structures. To enable molecular docking and MD simulations,
the channel was prepared using the Protein Preparation tool in the Maestro molecular
modeling suite [13]. Before the MD simulations, three potassium ions and two water
molecules were added to the selectivity filter (SF) of the channel. Additionally, missing side
chains and loops were filled. The Maestro's Prime module [14], [15] was employed to
incorporate the missing loops and side chains into the residues. PROPKA [16], [17] was used
to add hydrogen atoms to the protein at physiological pH, ensuring accurate ionization states
of amino acid residues. The structural optimization was then performed using the OPLS3 force
field with a convergence criterion of 0.3 Å RMSD for heavy atoms.
2.6
Receptor grid generation
The generation of a receptor grid is a crucial step in docking studies. It involves creating a
three-dimensional grid that represents the binding site of the receptor, which is necessary to
evaluate the binding energy of ligands during docking simulations. The Receptor Grid
Generation tool was utilized to identify the binding pocket (active site) in the structure. [18]

# Prepare Sub

In [28]:
import os
import re
import numpy as np
import pandas as pd

In [29]:
pred_14b = pd.read_parquet("./working/preds_14b.parquet")
pred_32b = pd.read_parquet("./working/preds_32b.parquet")
pred_72b = pd.read_parquet("./working/preds_72b.parquet")

pred_assumed = pd.read_parquet("./working/acc_preds_assumed.parquet")

sub_df = pd.concat([pred_72b, pred_32b, pred_32b, pred_14b, pred_assumed]).reset_index(drop=True)
# sub_df = pd.concat([pred_32b, pred_32b, pred_14b, pred_assumed]).reset_index(drop=True)

sub_df = sub_df.groupby(["article_id", "dataset_id"])["probs"].apply(lambda x: np.mean(x, axis=0)).reset_index()

sub_df.shape

(64, 3)

In [30]:
# pred_72b

In [31]:
base_df = pd.read_parquet("./working/base_pred_df.parquet")
family_df = pd.merge(base_df, sub_df, on=['article_id', 'dataset_id'], how='inner')
family_df = family_df.groupby(['article_id', 'family'])["probs"].apply(lambda x: np.mean(x, axis=0)).reset_index().rename(columns={'probs': 'family_probs'})
family_df.sample()

          article_id family                                       family_probs
12  10.1002_esp.5058    doi  [0.8585518983017569, 0.008752240721316846, 0.1...

In [32]:
base_df = pd.read_parquet("./working/base_pred_df.parquet")
oof_df = pd.merge(base_df, sub_df, on=['article_id', 'dataset_id'], how='left')
oof_df = oof_df.merge(family_df, on=['article_id', 'family'])

def fill_probs(row):
    try:
        return list(row['probs'])
    except Exception:
        return list(row['family_probs'])
    
oof_df['probs'] = oof_df.apply(lambda row: fill_probs(row), axis=1)
oof_df = oof_df.drop(columns=['family', 'family_probs']).reset_index(drop=True)
oof_df.shape

(64, 3)

In [33]:
oof_df

,article_id,dataset_id,probs
0,10.1002_2017jc013030,https://doi.org/10.17882/47142,"[0.27898905429144644, 0.5117241302197556, 0.20..."
1,10.1002_2017jc013030,https://doi.org/10.17882/49388,"[0.260569768340067, 0.5130554702563, 0.2263747..."
2,10.1002_cssc.202201821,https://doi.org/10.5281/zenodo.7074790,"[0.3217902428813044, 0.40419938118034, 0.27401..."
3,10.1002_ece3.3985,https://doi.org/10.4159/harvard.9780674433960,"[0.006859003104898642, 0.006493973618253573, 0..."
4,10.1002_ece3.4466,https://doi.org/10.5061/dryad.r6nq870,"[0.846957838615053, 4.888142627977436e-09, 0.1..."
...,...,...,...
59,10.1021_acsomega.3c06074,CHEMBL3422978,"[0.0, 1.0, 0.0]"
60,10.1021_acsomega.3c06074,CHEMBL572163,"[0.0, 1.0, 0.0]"
61,10.1021_acsomega.3c06074,CHEMBL1782574,"[0.0, 1.0, 0.0]"
62,10.1021_acsomega.3c06074,CHEMBL390649,"[0.0, 1.0, 0.0]"
63,10.1021_acsomega.3c06074,CHEMBL1257821,"[0.0, 1.0, 0.0]"

### Accession Removal based on sum of primary probs

In [34]:
import pandas as pd

def should_remove_accession_id(row, buffer, th=0.5):
    article_id = row["article_id"]
    dataset_id = row["dataset_id"]
    max_doi_prob = buffer.get(article_id, 0.0)

    if dataset_id.startswith("https://doi.org/"):
        return False

    if max_doi_prob > th:
        return True

    return False


# ----
buffer = dict()
for _, row in oof_df.iterrows():
    article_id = row["article_id"]
    dataset_id = row["dataset_id"]
    if dataset_id.startswith("https://doi.org/"):
        p = round(float(row["probs"][0]), 4)
        if article_id in buffer:
            buffer[article_id] += p
        else:
            buffer[article_id] = p

In [35]:
print(f"shape before: {oof_df.shape}")
oof_df["should_remove"] = oof_df.apply(lambda row: should_remove_accession_id(row, buffer, th=0.8), axis=1)
oof_df = oof_df[~oof_df["should_remove"]].reset_index(drop=True)
oof_df = oof_df.drop(columns=["should_remove"])
print(f"shape after: {oof_df.shape}")

shape before: (64, 3)
shape after: (64, 3)

### Filter NA

In [36]:
def type_filter_fn(row, doi_th, acc_th):
    is_doi = row["dataset_id"].startswith("https://doi.org/")
    
    if is_doi:
        return row["null_p"] <= doi_th
    else:
        return row["null_p"] <= acc_th

In [37]:
oof_df['null_p'] = oof_df['probs'].apply(lambda x: x[2])

doi_th = 0.6
acc_th = 0.9

oof_df["should_keep"] = oof_df.apply(lambda x: type_filter_fn(x, doi_th, acc_th), axis=1)
oof_df = oof_df[oof_df["should_keep"]].reset_index(drop=True)
oof_df = oof_df.drop(columns=["should_keep"])
oof_df = oof_df.reset_index(drop=True)

oof_df['type'] = oof_df['probs'].apply(lambda x: 'Primary' if x[0] > x[1] else 'Secondary')
oof_df['type'].value_counts()

type
Secondary    37
Primary      26
Name: count, dtype: int64

In [38]:
oof_df.shape

(63, 5)

# Submission

In [39]:
oof_df['row_id'] = range(len(oof_df))
oof_df = oof_df[oof_df["type"].isin(["Primary", "Secondary"])].reset_index(drop=True)
oof_df = oof_df.drop_duplicates(subset=['article_id', 'dataset_id'], keep="first").reset_index(drop=True)
oof_df = oof_df[['row_id', 'article_id', 'dataset_id', 'type']].copy()

oof_df

,row_id,article_id,dataset_id,type
0,0,10.1002_2017jc013030,https://doi.org/10.17882/47142,Secondary
1,1,10.1002_2017jc013030,https://doi.org/10.17882/49388,Secondary
2,2,10.1002_cssc.202201821,https://doi.org/10.5281/zenodo.7074790,Secondary
3,3,10.1002_ece3.4466,https://doi.org/10.5061/dryad.r6nq870,Primary
4,4,10.1002_ece3.5260,https://doi.org/10.5061/dryad.2f62927,Primary
...,...,...,...,...
58,58,10.1021_acsomega.3c06074,CHEMBL3422978,Secondary
59,59,10.1021_acsomega.3c06074,CHEMBL572163,Secondary
60,60,10.1021_acsomega.3c06074,CHEMBL1782574,Secondary
61,61,10.1021_acsomega.3c06074,CHEMBL390649,Secondary
62,62,10.1021_acsomega.3c06074,CHEMBL1257821,Secondary

In [40]:
oof_df.to_csv("submission.csv", index=False, columns=["row_id", "article_id", "dataset_id", "type"])

In [41]:
print("Final submission stats:")
print(oof_df["type"].value_counts())
print(f"Total entries: {len(oof_df)}")

Final submission stats:
type
Secondary    37
Primary      26
Name: count, dtype: int64
Total entries: 63

# Evaluate validation score

In [42]:
# Validation scoring
import os

def f1_score(tp, fp, fn):
    return 2 * tp / (2 * tp + fp + fn) if (2 * tp + fp + fn) != 0 else 0.0
    
if not os.getenv('KAGGLE_IS_COMPETITION_RERUN'):
    pred_df = pd.read_csv("submission.csv")

    label_df = pd.read_csv("/kaggle/input/make-data-count-finding-data-references/train_labels.csv")
    blacklist = set(label_df[label_df["type"] == "Missing"]["article_id"].unique().tolist())
    label_df = label_df[label_df['type'] != 'Missing'].reset_index(drop=True)

    pred_df = pred_df[~pred_df['article_id'].isin(blacklist)].reset_index(drop=True)

    hits_df = label_df.merge(pred_df, on=["article_id", "dataset_id", "type"])
    
    tp = hits_df.shape[0]
    fp = pred_df.shape[0] - tp
    fn = label_df.shape[0] - tp
    
    print("\nValidation Results:")
    print("TP:", tp)
    print("FP:", fp)
    print("FN:", fn)
    print("F1 Score:", round(f1_score(tp, fp, fn), 3))

Validation Results:
TP: 47
FP: 12
FN: 672
F1 Score: 0.121